### ISSUE TITLE
I can't add any subtitles

### ISSUE THREAD

**Issue by jesuu97** [popcorntime/popcorntime#1]
So that's basically it. I select the file but nothing happens. Thank you.

**Comment by tyrk2k** [comment]
In the last stable version found here https://ci.popcorntime.sh/job/Popcorn-Time-Desktop/18/ this bug has been fixed, at least in linux64 version.  

But Trakt.tv sync and Drag and drop still not working here.


 Downloaded from: https://ci.popcorntime.sh/job/Popcorn-Time-Desktop/18/artifact/Release/Popcorn-Time-Linux64.tar.xz

**Comment by edisoncast** [comment]
Same issue here (Linux 32 bits)

**Comment by tcitworld** [comment]
If I try to add some custom subtitles : 

```
>> [4025:0218/205850:INFO:CONSOLE(21)] 
""%c[%cERROR%c] TypeError: undefined is not a function" "color: black;" "color: red;" "color: black;" 
"TypeError: undefined is not a function\n 
at null.\u003Canonymous\u003E (app://host/src/app/lib/views/player/player.js:274:45)\n    
at triggerEvents (app://host/src/app/vendor/backbone/backbone.js:369:57)\n
at triggerApi (app://host/src/app/vendor/backbone/backbone.js:356:19)\n
at eventsApi (app://host/src/app/vendor/backbone/backbone.js:155:16)\n
at Events.trigger (app://host/src/app/vendor/backbone/backbone.js:346:5)\n
at CustomTrackMenuItem.loadSubtitle (app://host/src/app/vendor/videojsplugins.js:152:18)\n
at HTMLInputElement.\u003Canonymous\u003E (app://host/src/app/vendor/videojsplugins.js:124:22)\n
at HTMLInputElement.jQuery.event.dispatch (app://host/src/app/vendor/jquery/dist/jquery.js:4732:27)\n
at HTMLInputElement.elemData.handle (app://host/src/app/vendor/jquery/dist/jquery.js:4544:28)"", source: app://host/src/app/app.js (21)
>> [4025:0218/205850:INFO:CONSOLE(274)] "Uncaught TypeError: undefined is not a function", source: app://host/src/app/lib/views/player/player.js (274)
```

**Comment by brianardiles** [comment]
try the last build: http://ci.popcorntime.sh

**Comment by tcitworld** [comment]
I use the very last code on the master branch.

**Comment by edisoncast** [comment]
Hi, I downloaded the code but issue persists [4044:0219/142638:INFO:CONSOLE(21)] ""%c[%cERROR%c] TypeError: undefined is not a function" "color: black;" "color: red;" "color: black;" "TypeError: undefined is not a function\n    at null.\u003Canonymous\u003E (app://host/src/app/lib/views/player/player.js:274:45)\n    at triggerEvents (app://host/src/app/vendor/backbone/backbone.js:369:57)\n    at triggerApi (app://host/src/app/vendor/backbone/backbone.js:356:19)\n    at eventsApi (app://host/src/app/vendor/backbone/backbone.js:155:16)\n    at Events.trigger (app://host/src/app/vendor/backbone/backbone.js:346:5)\n    at CustomTrackMenuItem.loadSubtitle (app://host/src/app/vendor/videojsplugins.js:152:18)\n    at HTMLInputElement.\u003Canonymous\u003E (app://host/src/app/vendor/videojsplugins.js:124:22)\n    at HTMLInputElement.jQuery.event.dispatch (app://host/src/app/vendor/jquery/dist/jquery.js:4732:27)\n    at HTMLInputElement.elemData.handle (app://host/src/app/vendor/jquery/dist/jquery.js:4544:28)"", source: app://host/src/app/app.js (21)
[4044:0219/142638:INFO:CONSOLE(274)] "Uncaught TypeError: undefined is not a function", source: app://host/src/app/lib/views/player/player.js (274)
