### ISSUE TITLE
Popcorn-Time  doesn't load

### ISSUE THREAD

**Issue by ghost** [popcorntime/popcorntime#1027]
Operating System Version:
Mageia Linux 7

Popcorn Time Version:
0.3.10

Download date:
2019 July 12th

#### Expected Behaviour
It should load the available movies.

#### Actual Behaviour
The loading cursor stays.
...

#### Steps to reproduce the behaviour

1. Open Popcorn-Time
2. ...
3. ...

I obtain the following error in the logs:
app.js:21 [ERROR] Error: listen EADDRINUSE :::8008 Error: listen EADDRINUSE :::8008
    at Object.exports._errnoException (util.js:1026:11)
    at exports._exceptionWithHostPort (util.js:1049:20)
    at Server._listen2 (net.js:1257:14)
    at listen (net.js:1293:10)
    at Server.listen (net.js:1389:5)
    at Object.listen (/home/gouessej/Téléchargements/PopcornTime/node_modules/json-rpc2/src/server.js:65:18)
    at startListening (chrome-extension://hecfofbbdfadifpemejbbdcjmfmboohj/src/app/httpapi.js:734:29)
    at chrome-extension://hecfofbbdfadifpemejbbdcjmfmboohj/src/app/httpapi.js:762:17
    at Promise_then_fulfilled (/home/gouessej/Téléchargements/PopcornTime/node_modules/q/q.js:766:44)
    at Promise_done_fulfilled (/home/gouessej/Téléchargements/PopcornTime/node_modules/q/q.js:835:31)
    at Fulfilled_dispatch [as dispatch] (/home/gouessej/Téléchargements/PopcornTime/node_modules/q/q.js:1229:9)
    at Promise_done_task (/home/gouessej/Téléchargements/PopcornTime/node_modules/q/q.js:871:28)
    at RawTask.call (/home/gouessej/Téléchargements/PopcornTime/node_modules/asap/asap.js:40:19)
    at flush (/home/gouessej/Téléchargements/PopcornTime/node_modules/asap/raw.js:50:29)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)win.error @ app.js:21(anonymous function) @ app.js:699emitOne @ events.js:101emit @ events.js:188process._fatalException @ bootstrap_node.js:313
app.js:21 [ERROR] updater.update() Error: write EPROTO(…)win.error @ app.js:21(anonymous function) @ database.js:435Promise_then_rejected @ /home/gouessej/Téléchargements/PopcornTime/node_modules/q/q.js:779Promise_done_rejected @ /home/gouessej/Téléchargements/PopcornTime/node_modules/q/q.js:861Rejected_then @ /home/gouessej/Téléchargements/PopcornTime/node_modules/q/q.js:1323Rejected_dispatch @ /home/gouessej/Téléchargements/PopcornTime/node_modules/q/q.js:1311Pending_become_eachMessage_task @ /home/gouessej/Téléchargements/PopcornTime/node_modules/q/q.js:1369RawTask.call @ /home/gouessej/Téléchargements/PopcornTime/node_modules/asap/asap.js:40flush @ /home/gouessej/Téléchargements/PopcornTime/node_modules/asap/raw.js:50_combinedTickCallback @ internal/process/next_tick.js:67_tickCallback @ internal/process/next_tick.js:98

901Navigated to chrome-extension://hecfofbbdfadifpemejbbdcjmfmboohj/src/app/index.html

I tried to use another DNS and I used --disable-gpu to get rid of an error message but it still doesn't work.

**Comment by ghost** [comment]
I obtain the following error messages and warnings in the logs:
/home/gouessej/Téléchargements/PopcornTime/node_modules/iconv-lite/lib/extend-node.js:17 ACTION NEEDED: require('iconv-lite').extendNodeEncodings() is not supported in your version of NodeextendNodeEncodings @ /home/gouessej/Téléchargements/PopcornTime/node_modules/iconv-lite/lib/extend-node.js:17
/home/gouessej/Téléchargements/PopcornTime/node_modules/iconv-lite/lib/extend-node.js:18 See more info at https://github.com/ashtuchkin/iconv-lite/wiki/Node-v4-compatibilityextendNodeEncodings @ /home/gouessej/Téléchargements/PopcornTime/node_modules/iconv-lite/lib/extend-node.js:18

/home/gouessej/Téléchargements/PopcornTime/node_modules/iconv-lite/lib/extend-node.js:18 See more info at https://github.com/ashtuchkin/iconv-lite/wiki/Node-v4-compatibilityextendNodeEncodings @ /home/gouessej/Téléchargements/PopcornTime/node_modules/iconv-lite/lib/extend-node.js:18
/home/gouessej/Téléchargements/PopcornTime/node_modules/butter-provider/index.js:9 value urlList was not provided(anonymous function) @ /home/gouessej/Téléchargements/PopcornTime/node_modules/butter-provider/index.js:9

/home/gouessej/Téléchargements/PopcornTime/node_modules/butter-provider/index.js:9 value urlList was not provided(anonymous function) @ /home/gouessej/Téléchargements/PopcornTime/node_modules/butter-provider/index.js:9
/home/gouessej/Téléchargements/PopcornTime/node_modules/butter-provider-movies/index.js:92 Request to MovieApi https://movies-v2.api-fetch.website/movies/1?sort=trending&limit=50&genre=All&order=-1

/home/gouessej/Téléchargements/PopcornTime/node_modules/butter-provider-movies/index.js:95 MovieAPI endpoint 'https://movies-v2.api-fetch.website/' failed.(anonymous function) @ /home/gouessej/Téléchargements/PopcornTime/node_modules/butter-provider-movies/index.js:95

**Comment by ghost** [comment]
It's caused by a regression in Mageia 7: https://bugs.mageia.org/show_bug.cgi?id=24835
