### ISSUE TITLE
Error converting subtitles

### ISSUE THREAD

**Issue by harmonymeow** [popcorntime/popcorntime#1182]
Operating System Version:
Windows 10

Popcorn Time Version:
Build #391 

Download date:
3/20/2020

#### Expected Behaviour
Subtitles are loaded
...

#### Actual Behaviour
Error message: Subtitles not converted.
...

#### Steps to reproduce the behaviour
Try to play StarTrek: Picard S3E9 with English subtitles.

Logs:
app.js:11 [INFO] Loading torrent
app.js:11 [INFO] Returning cached provider OpenSubtitles
app.js:11 [INFO] Loading torrent: startingDownload
app.js:11 [INFO] Loading torrent: downloading
app.js:11 [INFO] Loading torrent: playingExternally
app.js:11 [INFO] Launching External Player: "C:\Program Files\VideoLAN\VLC\vlc.exe" --no-video-title-show http://127.0.0.1:64326/0
app.js:11 [INFO] 6 subtitles found
app.js:21 [ERROR] error converting subtitles TypeError [ERR_INVALID_CALLBACK]: Callback must be a function. Received 'utf8'
    at maybeCallback (fs.js:147:9)
    at Object.writeFile (fs.js:1271:14)
    at chrome-extension://hecfofbbdfadifpemejbbdcjmfmboohj/src/app/lib/subtitle/generic.js:149:28
    at Object.parse (C:\Users\aa001\AppData\Local\Popcorn-Time\node_modules\node-captions\lib\srt.js:95:20)
    at chrome-extension://hecfofbbdfadifpemejbbdcjmfmboohj/src/app/lib/subtitle/generic.js:144:34
    at n.decode (chrome-extension://hecfofbbdfadifpemejbbdcjmfmboohj/src/app/lib/subtitle/generic.js:177:17)
    at c.Channel.convert (chrome-extension://hecfofbbdfadifpemejbbdcjmfmboohj/src/app/lib/subtitle/generic.js:143:22)
    at _ (chrome-extension://hecfofbbdfadifpemejbbdcjmfmboohj/node_modules/backbone/backbone-min.js:1:3984)
    at m (chrome-extension://hecfofbbdfadifpemejbbdcjmfmboohj/node_modules/backbone/backbone-min.js:1:3712)
    at f (chrome-extension://hecfofbbdfadifpemejbbdcjmfmboohj/node_modules/backbone/backbone-min.js:1:1565)
    at c.Channel.u.trigger (chrome-extension://hecfofbbdfadifpemejbbdcjmfmboohj/node_modules/backbone/backbone-min.js:1:3592)
    at WebTorrentStreamer.<anonymous> (chrome-extension://hecfofbbdfadifpemejbbdcjmfmboohj/src/app/lib/streamer.js:401:38)
    at _ (chrome-extension://hecfofbbdfadifpemejbbdcjmfmboohj/node_modules/backbone/backbone-min.js:1:3926)
    at m (chrome-extension://hecfofbbdfadifpemejbbdcjmfmboohj/node_modules/backbone/backbone-min.js:1:3712)
    at f (chrome-extension://hecfofbbdfadifpemejbbdcjmfmboohj/node_modules/backbone/backbone-min.js:1:1565)
    at c.Channel.u.trigger (chrome-extension://hecfofbbdfadifpemejbbdcjmfmboohj/node_modules/backbone/backbone-min.js:1:3592)
    at chrome-extension://hecfofbbdfadifpemejbbdcjmfmboohj/src/app/lib/subtitle/generic.js:119:30
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
win.error @ app.js:21
(anonymous) @ streamer.js:406
convert @ generic.js:165
_ @ backbone.js:370
m @ backbone.js:356
f @ backbone.js:155
u.trigger @ backbone.js:346
(anonymous) @ streamer.js:401
_ @ backbone.js:369
m @ backbone.js:356
f @ backbone.js:155
u.trigger @ backbone.js:346
(anonymous) @ generic.js:119
processTicksAndRejections @ internal/process/task_queues.js:97

**Comment by team-pct** [comment]
Issue with opensubtitle
