### ISSUE TITLE
EXPORT DATABASE

### ISSUE THREAD

**Issue by Leoxur** [popcorntime/popcorntime#1196]
Operating System Version:

Windows 10 Pro 1909 18363.720
Popcorn Time Version:

0.4.1
Download date:

21/03/2020
#### Expected Behaviour

... "EXPORT DATABASE" should back up your viewed movies / TV shows and favorites

#### Actual Behaviour

...Do nothing

#### Steps to reproduce the behaviour

1. ... Settings "advanced"
2. ...Export Database
3. ...Choose folder and Select

**Comment by team-pct** [comment]
Before export database , please open console ( F12 ) and click on export database and let us know the error you are having

**Comment by Leoxur** [comment]
settings_container.js:618 :
Error: EISDIR: illegal operation on a directory, read
    at Object.readSync (fs.js:537:3)
    at tryReadSync (fs.js:352:20)
    at Object.readFileSync (fs.js:389:19)
    at Object.addLocalFile (C:\Users\everl\AppData\Local\Popcorn-Time\node_modules\adm-zip\adm-zip.js:226:35)
    at chrome-extension://hecfofbbdfadifpemejbbdcjmfmboohj/src/app/lib/views/settings_container.js:609:29
    at Array.forEach (<anonymous>)
    at HTMLInputElement.<anonymous> (chrome-extension://hecfofbbdfadifpemejbbdcjmfmboohj/src/app/lib/views/settings_container.js:608:35)
    at HTMLInputElement.dispatch (chrome-extension://hecfofbbdfadifpemejbbdcjmfmboohj/node_modules/jquery/dist/jquery.min.js:2:41772)
    at HTMLInputElement.y.handle (chrome-extension://hecfofbbdfadifpemejbbdcjmfmboohj/node_modules/jquery/dist/jquery.min.js:2:39791)

app.js:26  :
[WARNING] Setting not defined: undefined
win.warn @ app.js:26
saveSetting @ settings_container.js:273
N @ underscore-min.js:5
(anonymous) @ underscore-min.js:5
(anonymous) @ underscore-min.js:5
dispatch @ jquery.min.js:2
y.handle @ jquery.min.js:2

app.js:17 :
[INFO] Setting changed: undefined - false

**Comment by team-pct** [comment]
Working fine on oSX , i will try to look into a Windows machine later today

**Comment by kiriles90** [comment]
@Persei08 this is fixed, close please
