### ISSUE TITLE
Unable to grunt start due to ES6 issues

### ISSUE THREAD

**Issue by sidazhang** [popcorntime/popcorntime#163]
Operating System Version:
OS X 10.11.4

Node Version:
v0.10.32

NPM Version:
2.8.2

Popcorn Time Version:
Latest development build: 4f15b03b21411c86446e606d5e096310b8511e2a

Download date:
May 7th, 2016
#### Steps to repoduce the behaviour

Having some issues running `grunt start`
grunt start
Running "start" task

Seems like an issue with running ES6 code

```
Running "exec:osx32" (exec) task
>> [79650:0507/164047:ERROR:nw_shell.cc(335)] /Users/sidazhang/scripts/popcorn-desktop/node_modules/peerflix/node_modules/torrent-stream/node_modules/fs-chunk-store/node_modules/path-exists/index.js:4
>> module.exports = fp => new Promise(resolve => {
>>                     ^^
>> SyntaxError: Unexpected token =>
>>     at exports.runInThisContext (vm.js:53:16)
>>     at Module._compile (module.js:434:25)
>>     at Object.Module._extensions..js (module.js:469:10)
>>     at Module.load (module.js:346:32)
>>     at Function.Module._load (module.js:301:12)
>>     at Module.require (module.js:356:17)
>>     at require (module.js:375:17)
>>     at Object.<anonymous> (/Users/sidazhang/scripts/popcorn-desktop/node_modules/peerflix/node_modules/torrent-stream/node_modules/fs-chunk-store/index.js:8:18)
>>     at Module._compile (module.js:451:26)
>>     at Object.Module._extensions..js (module.js:469:10)
>> [79650:0507/164047:INFO:CONSOLE(4)] "Uncaught SyntaxError: /Users/sidazhang/scripts/popcorn-desktop/node_modules/peerflix/node_modules/torrent-stream/node_modules/fs-chunk-store/node_modules/path-exists/index.js:4
>> module.exports = fp => new Promise(resolve => {
>>                     ^^
>> Unexpected token =>", source: /Users/sidazhang/scripts/popcorn-desktop/node_modules/peerflix/node_modules/torrent-stream/node_modules/fs-chunk-store/node_modules/path-exists/index.js (4)
>> [79650:0507/164047:INFO:CONSOLE(6)] ""Database path: /Users/sidazhang/Library/Application Support/Popcorn-Time"", source: app://host/src/app/database.js (6)
```

**Comment by sidazhang** [comment]
Added js-flags into package.json

```
  "js-flags": "--harmony --harmony_arrow_functions",
```

This fixes the issue.
