### ISSUE TITLE
Error: File not found with singular glob while yarn dist --platforms=win64 on Arch Linux x64

### ISSUE THREAD

**Issue by vageliskatsiotis** [popcorntime/popcorntime#1704]
Hi all.
While trying to compile from latest development src for Win64 I get the following error on Arch Linux x64
Installation on Linux completed successfully.

```
Error: File not found with singular glob: /home/vagelis/Documents/popcorn-desktop-development/build/Popcorn-Time-0.4.4-win64-Setup.exe (if this was purposeful, use `allowEmpty` option)
    at Glob.<anonymous> (/home/vagelis/Documents/popcorn-desktop-development/node_modules/glob-stream/readable.js:84:17)
    at Object.onceWrapper (events.js:421:26)
    at Glob.emit (events.js:314:20)
    at Glob.EventEmitter.emit (domain.js:486:12)
    at Glob._finish (/home/vagelis/Documents/popcorn-desktop-development/node_modules/glob/glob.js:197:8)
    at done (/home/vagelis/Documents/popcorn-desktop-development/node_modules/glob/glob.js:182:14)
    at Glob._processSimple2 (/home/vagelis/Documents/popcorn-desktop-development/node_modules/glob/glob.js:688:12)
    at /home/vagelis/Documents/popcorn-desktop-development/node_modules/glob/glob.js:676:10
    at Glob._stat2 (/home/vagelis/Documents/popcorn-desktop-development/node_modules/glob/glob.js:772:12)
    at lstatcb_ (/home/vagelis/Documents/popcorn-desktop-development/node_modules/glob/glob.js:764:12)
[15:48:26] 'dist' errored after 1.23 min
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

```
It's seems that this has changed from gulp 3 to gulp 4

https://github.com/gulpjs/gulp/issues/2282

**Comment by Persei08** [comment]
@vageliskatsiotis @riclas ,  I think you have another error related to makensis before the error you show both us. (Here and in #1719 )

Plz, Install makensis v3+ (nsis on windows) and retry.

My config just in case:
```
$ node -v && npm -v && yarn -v && makensis -version
v13.11.0
6.13.7
1.22.10
v3.05-2
```

my logs (ubuntu 20.04)
```
yarn dist --platforms=win64
yarn run v1.22.10
$ gulp dist --platforms=win64
[18:58:40] Using gulpfile ~/dev/butter/popcorn-desktop/gulpfile.js
[18:58:40] Starting 'dist'...
[18:58:40] Starting 'build'...
[18:58:40] Starting 'injectgit'...
Branch: development
Commit: 91a57276
[18:58:40] Finished 'injectgit' after 27 ms
[18:58:40] Starting 'css'...
Stylus files compiled in /home/anto/dev/butter/popcorn-desktop/src/app/themes/
[18:58:48] Finished 'css' after 7.4 s
[18:58:48] Starting 'nwjs'...
Error: Command failed: npm ls --production=true --parseable=true
npm ERR! missing: colour@latest, required by ascli@0.3.0
npm ERR! missing: optjs@latest, required by ascli@0.3.0
npm ERR! missing: vtt.js@git+https://github.com/gkatsev/vtt.js.git#vjs-v0.12.1, required by video.js@4.12.15
npm ERR! missing: http-node@github:feross/http-node#webtorrent, required by webtorrent@0.107.17

    at ChildProcess.exithandler (child_process.js:303:12)
    at ChildProcess.emit (events.js:315:20)
    at ChildProcess.EventEmitter.emit (domain.js:547:15)
    at maybeClose (internal/child_process.js:1026:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5) {
  killed: false,
  code: 1,
  signal: null,
  cmd: 'npm ls --production=true --parseable=true'
}
Using v0.44.5 (sdk)
Create cache folder in /home/anto/dev/butter/popcorn-desktop/cache/0.44.5-sdk
Downloading: https://get.popcorntime.app/repo/nw/v0.44.5/nwjs-sdk-v0.44.5-win-x64.zip
  downloading [====================] 100% 0.0s

Create release folder in /home/anto/dev/butter/popcorn-desktop/build/Popcorn-Time/win64
[19:01:47] Finished 'nwjs' after 2.98 min
[19:01:47] Starting '<anonymous>'...
[19:01:47] Finished '<anonymous>' after 1.46 ms
[19:01:47] Finished 'build' after 3.1 min
[19:01:47] Starting 'compresszip'...
Packaging zip for: win64
win64 zip packaged in /home/anto/dev/butter/popcorn-desktop/build
[19:02:55] Finished 'compresszip' after 1.12 min
[19:02:55] Starting 'deb'...
No `deb` task for: win64
[19:02:55] Finished 'deb' after 1.79 ms
[19:02:55] Starting 'mac-pkg'...
Packaging deb is only possible on osx
[19:02:55] Finished 'mac-pkg' after 767 μs
[19:02:55] Starting 'nsis'...
Packaging nsis for: win64
win64 nsis packaged in /home/anto/dev/butter/popcorn-desktop/build
[19:07:15] Finished 'nsis' after 4.32 min
[19:07:15] Starting 'prepareUpdater'...
No `compress` task for: win64
[19:07:15] Finished 'prepareUpdater' after 703 μs
[19:07:15] Starting 'prepareUpdater:win'...
win64 zip packaged in /home/anto/dev/butter/popcorn-desktop/build
[19:07:21] Finished 'prepareUpdater:win' after 6.09 s
[19:07:21] Starting 'compressUpdater'...
Windows updater is already compressed
[19:07:21] Finished 'compressUpdater' after 1.4 ms
[19:07:21] Starting 'cleanForDist'...
Deleted: 
 /home/anto/dev/butter/popcorn-desktop/build/Popcorn-Time
[19:07:22] Finished 'cleanForDist' after 1.88 s
[19:07:22] Starting 'clean:updater'...
Nothing to delete
[19:07:22] Finished 'clean:updater' after 1.39 ms
[19:07:22] Starting 'clean:updater:win'...
Deleted build files :
 /home/anto/dev/butter/popcorn-desktop/build/update.exe
[19:07:23] Finished 'clean:updater:win' after 22 ms
[19:07:23] Starting '<anonymous>'...
[19:07:23] Finished '<anonymous>' after 352 μs
[19:07:23] Finished 'dist' after 8.7 min
Done in 523.29s.
```

Probably, some little improvements to do in the gulpfile... like checking makensis version >3 (v2 was generating issue) and mac-pkg task saying 'deb' instead of 'pkg'.

Let me know if it solve your issues or not.

**Comment by vageliskatsiotis** [comment]
@Persei08 Windows build throws this now.. I've installled nsis 3 also.
```

C:\Users\Vagelis\Downloads\popcorn-desktop-development>yarn install --ignore-engines
yarn install v1.22.5
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@1.2.4: The platform "win32" is incompatible with this module.
info "fsevents@1.2.4" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
[4/4] Building fresh packages...
[-/4] ⢀ waiting...
[-/4] ⢀ waiting...
[3/4] ⢀ utf-8-validate
error C:\Users\Vagelis\Downloads\popcorn-desktop-development\node_modules\guppy-pre-commit: Command failed.
Exit code: 4
Command: guppy pre-commit
Arguments:
Directory: C:\Users\Vagelis\Downloads\popcorn-desktop-development\node_modules\guppy-pre-commit
Output:
```

**Comment by riclas** [comment]
Persei i did install nsis and the build finished fine. but when i use it to install the app, it doesn't launch

**Comment by Persei08** [comment]
@vageliskatsiotis is your branch updates to latest commit ? I don't have this issue here 

```
$ yarn install --ignore-engines
yarn install v1.22.5
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@1.2.4: The platform "win32" is incompatible with this module.
info "fsevents@1.2.4" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
[4/4] Building fresh packages...
Done in 120.36s.
```
Can you give me the output of:
- `node -v && npm -v && yarn -v && makensis -version` 
and also `git log --oneline -1`

@riclas, I'll try again, and tell you more

**Comment by Persei08** [comment]
@riclas for me everything is working the setup.exe works as expected and the installed PCT too.

I suggest you guys try again but with same parameters than me.

First check your programs versions
`node -v` : v13.11.0
`npm -v` : 6.13.7
`yarn -v` : 1.22.5
`makensis -VERSION` (linux : 3.05-2) or `makensis /VERSION` (windows : 3.06) ...  but i think it should be at least 3.01 if I remember well

Then in your local branch, check you have the latest commit:
`git log --oneline -1` => (91a57276 (...) Merge pull request #1732 from kiriles90/toggle_subs_keyb) 

if not, then update it.

if everything ok, then do `git clean -f`
then `git reset hard` to be sure you doesn't have any modified file
then `yarn clean`.

then all the usual steps : 
- `yarn config set yarn-offline-mirror ./node_modules/`
- `yarn install --ignore-engines`
- `yarn dist --platforms=win64`

If you have issue at some point, paste your terminal output.

**Comment by riclas** [comment]
edit: i updated node

when building i get the following output:
npm ERR! missing: colour@latest, required by ascli@0.3.0
npm ERR! missing: optjs@latest, required by ascli@0.3.0
npm ERR! missing: vtt.js@git+https://github.com/gkatsev/vtt.js.git#vjs-v0.12.1, required by video.js@4.12.15
npm ERR! missing: http-node@github:feross/http-node#webtorrent, required by webtorrent@0.107.17

yet, it builds the installer and for some reason it now runs after installing. yhey!

**Comment by Persei08** [comment]
>yet, it builds the installer and for some reason it now runs after installing. yhey!

Ok, nice ;)

the npm ERR lines here can be ignored, they are related to `npm ls --production=true --parseable=true` cmd, which is called to get node_modules list and If i remember correctly then be passed to nw-builder... this error happen since months (if not years) ... not sure if it somehow works or if something else fix the thing later, but at the end the app works :D

**Comment by vageliskatsiotis** [comment]
I'll give it another shot and let you know soon

**Comment by vageliskatsiotis** [comment]
Confirmed built on Arch x64 for Windows 64, installed and ran on Windows 10. One thing though, installation on top of previous installation removes all config and dbs from data folder and no desktop shortcut in the end.

**Comment by Persei08** [comment]
@vageliskatsiotis Ok thx for feedback. For the installer issue which delete previous install conf/settings, see issues #1579 and #1247 
So, i close this one since you both now have a working build. :)

**Comment by tpw1314** [comment]
Hi, I am facing the same issue, i just clone development branch today.
OS : Windows 10
I tried npm install and yarn add makensis, but this command does not work.

`C:\xampp\htdocs\popcorn-desktop>node -v && npm -v && yarn -v && makensis -version
v14.17.0
6.14.13
1.22.10
'makensis' is not recognized as an internal or external command,
operable program or batch file.`

npm also yarn attempt to add makensis, succeed but cannot run command
`+ makensis@0.23.4
added 99 packages from 44 contributors, removed 162 packages, updated 1025 packages and audited 1184 packages in 176.202s

52 packages are looking for funding
  run `npm fund` for details

found 23 vulnerabilities (10 low, 13 high)
  run `npm audit fix` to fix them, or `npm audit` for details`

yarn install --ignore-engines is fine
`C:\xampp\htdocs\popcorn-desktop>yarn install --ignore-engines
yarn install v1.22.10
[1/4] Resolving packages...
success Already up-to-date.
Done in 0.85s.`

The error when dist command ran -
```
C:\xampp\htdocs\popcorn-desktop>yarn dist --platforms=win64
yarn run v1.22.10
$ gulp dist --platforms=win64
(node:296) Warning: Accessing non-existent property 'lineno' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
(node:296) Warning: Accessing non-existent property 'column' of module exports inside circular dependency
(node:296) Warning: Accessing non-existent property 'filename' of module exports inside circular dependency
(node:296) Warning: Accessing non-existent property 'lineno' of module exports inside circular dependency
(node:296) Warning: Accessing non-existent property 'column' of module exports inside circular dependency
(node:296) Warning: Accessing non-existent property 'filename' of module exports inside circular dependency
[11:48:22] Using gulpfile C:\xampp\htdocs\popcorn-desktop\gulpfile.js
[11:48:22] Starting 'dist'...
[11:48:22] Starting 'build'...
[11:48:22] Starting 'injectgit'...
Branch: development
Commit: 4b759320
[11:48:22] Finished 'injectgit' after 73 ms
[11:48:22] Starting 'css'...
Stylus files compiled in C:\xampp\htdocs\popcorn-desktop\src\app\themes\
[11:48:29] Finished 'css' after 6.21 s
[11:48:29] Starting 'nwjs'...
Error: Command failed: npm ls --production=true --parseable=true
npm ERR! invalid: webtorrent@0.118.0 C:\xampp\htdocs\popcorn-desktop\node_modules\webtorrent
npm ERR! missing: bittorrent-protocol@git+https://github.com/popcorn-time-ru/bittorrent-protocol.git#pe-mse-update, required by webtorrent@0.118.0
npm ERR! missing: http-node@github:feross/http-node#webtorrent, required by webtorrent@0.118.0
npm ERR! extraneous: bitfield@4.0.0 C:\xampp\htdocs\popcorn-desktop\node_modules\bitfield
npm ERR! extraneous: bittorrent-dht@10.0.0 C:\xampp\htdocs\popcorn-desktop\node_modules\bittorrent-dht
npm ERR! extraneous: chrome-net@3.3.4 C:\xampp\htdocs\popcorn-desktop\node_modules\chrome-net
npm ERR! extraneous: chunk-store-stream@4.3.0 C:\xampp\htdocs\popcorn-desktop\node_modules\chunk-store-stream
npm ERR! extraneous: cpus@1.0.3 C:\xampp\htdocs\popcorn-desktop\node_modules\cpus
npm ERR! extraneous: create-torrent@4.7.0 C:\xampp\htdocs\popcorn-desktop\node_modules\create-torrent
npm ERR! extraneous: fs-chunk-store@2.0.3 C:\xampp\htdocs\popcorn-desktop\node_modules\fs-chunk-store
npm ERR! extraneous: immediate-chunk-store@2.1.1 C:\xampp\htdocs\popcorn-desktop\node_modules\immediate-chunk-store
npm ERR! extraneous: load-ip-set@2.2.1 C:\xampp\htdocs\popcorn-desktop\node_modules\load-ip-set
npm ERR! extraneous: lt_donthave@1.0.1 C:\xampp\htdocs\popcorn-desktop\node_modules\lt_donthave
npm ERR! extraneous: memory-chunk-store@1.3.2 C:\xampp\htdocs\popcorn-desktop\node_modules\memory-chunk-store
npm ERR! extraneous: multistream@4.1.0 C:\xampp\htdocs\popcorn-desktop\node_modules\multistream
npm ERR! extraneous: package-json-versionify@1.0.4 C:\xampp\htdocs\popcorn-desktop\node_modules\package-json-versionify
npm ERR! extraneous: render-media@4.1.0 C:\xampp\htdocs\popcorn-desktop\node_modules\render-media
npm ERR! extraneous: run-parallel-limit@1.1.0 C:\xampp\htdocs\popcorn-desktop\node_modules\run-parallel-limit
npm ERR! extraneous: simple-sha1@3.1.0 C:\xampp\htdocs\popcorn-desktop\node_modules\simple-sha1
npm ERR! extraneous: speedometer@1.1.0 C:\xampp\htdocs\popcorn-desktop\node_modules\speedometer
npm ERR! extraneous: stream-to-blob@2.0.1 C:\xampp\htdocs\popcorn-desktop\node_modules\stream-to-blob
npm ERR! extraneous: stream-to-blob-url@3.0.2 C:\xampp\htdocs\popcorn-desktop\node_modules\stream-to-blob-url
npm ERR! extraneous: stream-with-known-length-to-buffer@1.0.4 C:\xampp\htdocs\popcorn-desktop\node_modules\stream-with-known-length-to-buffer
npm ERR! extraneous: torrent-discovery@9.4.0 C:\xampp\htdocs\popcorn-desktop\node_modules\torrent-discovery
npm ERR! extraneous: torrent-piece@2.0.1 C:\xampp\htdocs\popcorn-desktop\node_modules\torrent-piece
npm ERR! extraneous: ut_metadata@3.5.2 C:\xampp\htdocs\popcorn-desktop\node_modules\ut_metadata
npm ERR! extraneous: ut_pex@2.0.1 C:\xampp\htdocs\popcorn-desktop\node_modules\ut_pex
npm ERR! extraneous: utp-native@2.4.0 C:\xampp\htdocs\popcorn-desktop\node_modules\utp-native
npm ERR! extraneous: mime@2.5.2 C:\xampp\htdocs\popcorn-desktop\node_modules\webtorrent\node_modules\mime
npm ERR! extraneous: parse-torrent@9.1.3 C:\xampp\htdocs\popcorn-desktop\node_modules\webtorrent\node_modules\parse-torrent
npm ERR! extraneous: readable-stream@3.6.0 C:\xampp\htdocs\popcorn-desktop\node_modules\webtorrent\node_modules\readable-stream
npm ERR! missing: vtt.js@git+https://github.com/gkatsev/vtt.js.git#vjs-v0.12.1, required by video.js@4.12.15

    at ChildProcess.exithandler (child_process.js:319:12)
    at ChildProcess.emit (events.js:376:20)
    at ChildProcess.emit (domain.js:532:15)
    at maybeClose (internal/child_process.js:1055:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
    at Process.callbackTrampoline (internal/async_hooks.js:134:14) {
  killed: false,
  code: 1,
  signal: null,
  cmd: 'npm ls --production=true --parseable=true'
}
Error: getaddrinfo EAI_AGAIN popcorntime.app
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:67:26)
    at GetAddrInfoReqWrap.callbackTrampoline (internal/async_hooks.js:134:14) {
  errno: -3001,
  code: 'EAI_AGAIN',
  syscall: 'getaddrinfo',
  hostname: 'popcorntime.app'
}
[11:49:16] Finished 'nwjs' after 48 s
[11:49:16] Starting '<anonymous>'...
[11:49:16] Finished '<anonymous>' after 1.27 ms
[11:49:16] Finished 'build' after 54 s
[11:49:16] Starting 'compresszip'...
Packaging zip for: win64
win64 zip packaged in C:\xampp\htdocs\popcorn-desktop\build
[11:49:17] Finished 'compresszip' after 16 ms
[11:49:17] Starting 'deb'...
No `deb` task for: win64
[11:49:17] Finished 'deb' after 2.16 ms
[11:49:17] Starting 'mac-pkg'...
Packaging deb is only possible on osx
[11:49:17] Finished 'mac-pkg' after 1.95 ms
[11:49:17] Starting 'nsis'...
Packaging nsis for: win64
Error: spawn makensis.exe ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:269:19)
    at onErrorNT (internal/child_process.js:467:16)
    at processTicksAndRejections (internal/process/task_queues.js:82:21) {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'spawn makensis.exe',
  path: 'makensis.exe',
  spawnargs: [
    './dist/windows/installer_makensis.nsi',
    '-DARCH=win64',
    '-DOUTDIR=C:\\xampp\\htdocs\\popcorn-desktop\\build'
  ]
}
win64 failed to package nsis
[11:49:17] Finished 'nsis' after 13 ms
[11:49:17] Starting 'prepareUpdater'...
No `compress` task for: win64
[11:49:17] Finished 'prepareUpdater' after 1.91 ms
[11:49:17] Starting 'prepareUpdater:win'...
[11:49:17] 'prepareUpdater:win' errored after 9.9 ms
[11:49:17] Error: File not found with singular glob: C:\xampp\htdocs\popcorn-desktop\build\Popcorn-Time-0.4.4-win64-Setup.exe (if this was purposeful, use `allowEmpty` option)
    at Glob.<anonymous> (C:\xampp\htdocs\popcorn-desktop\node_modules\glob-stream\readable.js:84:17)
    at Object.onceWrapper (events.js:483:26)
    at Glob.emit (events.js:376:20)
    at Glob.emit (domain.js:470:12)
    at Glob._finish (C:\xampp\htdocs\popcorn-desktop\node_modules\glob\glob.js:197:8)
    at done (C:\xampp\htdocs\popcorn-desktop\node_modules\glob\glob.js:182:14)
    at Glob._processSimple2 (C:\xampp\htdocs\popcorn-desktop\node_modules\glob\glob.js:688:12)
    at C:\xampp\htdocs\popcorn-desktop\node_modules\glob\glob.js:676:10
    at Glob._stat2 (C:\xampp\htdocs\popcorn-desktop\node_modules\glob\glob.js:772:12)
    at lstatcb_ (C:\xampp\htdocs\popcorn-desktop\node_modules\glob\glob.js:764:12)
[11:49:17] 'dist' errored after 54 s
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by tpw1314** [comment]
@ivan1986  @kiriles90 please read my problem with NSIS here from third to seventh paragraph. I did install NSIS but still did not work. Kindly elaborate what other NSIS I have to install ?

**Comment by kiriles90** [comment]
@tpw1314 Check what @Persei08 said in https://github.com/popcorn-official/popcorn-desktop/issues/1704#issuecomment-705827090. It works for everyone else.
