### ISSUE TITLE
Close button doesn't work after fullscreen

### ISSUE THREAD

**Issue by DK013** [popcorntime/popcorntime#1778]
Operating System Version:
Windows 10 Build 19041.572

Popcorn Time Version:
4.4 (HEAD - b2007344)

Download date:
Long Time ago

#### Expected Behaviour
Close button supposed to close/terminate the app

#### Actual Behaviour
Nothing
...

#### Steps to reproduce the behaviour

1. Start playing something
2. go fullscreen and back
3. click close button

The error looks like happenning because the temp directory deletion doesn't have the force flag

#### Screenshot(s) of issue or error(s) logs of developer console (Windows/Linux: F12, MacOS: ⌘ + 0 ... then 'console' tab) (recommended)

```
Error in event handler: Error: ENOTEMPTY: directory not empty, rmdir 'C:\Users\DK\AppData\Local\Temp\Popcorn-Time\37e77490bc4f285dbfa837514715a20bd405a502\Spider-Man Far From Home (2019) [WEBRip] [1080p] [YTS.LT]'
    at Object.rmdirSync (fs.js:789:3)
    at rmkidsSync (C:\Users\DK\AppData\Local\Popcorn-Time\node_modules\rimraf\rimraf.js:356:25)
    at rmdirSync (C:\Users\DK\AppData\Local\Popcorn-Time\node_modules\rimraf\rimraf.js:334:7)
    at rimrafSync (C:\Users\DK\AppData\Local\Popcorn-Time\node_modules\rimraf\rimraf.js:304:9)
    at C:\Users\DK\AppData\Local\Popcorn-Time\node_modules\rimraf\rimraf.js:342:5
    at Array.forEach (<anonymous>)
    at rmkidsSync (C:\Users\DK\AppData\Local\Popcorn-Time\node_modules\rimraf\rimraf.js:341:26)
    at rmdirSync (C:\Users\DK\AppData\Local\Popcorn-Time\node_modules\rimraf\rimraf.js:334:7)
    at rimrafSync (C:\Users\DK\AppData\Local\Popcorn-Time\node_modules\rimraf\rimraf.js:304:9)
    at C:\Users\DK\AppData\Local\Popcorn-Time\node_modules\rimraf\rimraf.js:342:5
    at Array.forEach (<anonymous>)
    at rmkidsSync (C:\Users\DK\AppData\Local\Popcorn-Time\node_modules\rimraf\rimraf.js:341:26)
    at rmdirSync (C:\Users\DK\AppData\Local\Popcorn-Time\node_modules\rimraf\rimraf.js:334:7)
    at Function.rimrafSync [as sync] (C:\Users\DK\AppData\Local\Popcorn-Time\node_modules\rimraf\rimraf.js:304:9)
    at deleteFolder (<URL>)
    at close (<URL>)
    at NWWindow.<anonymous> (<URL>)
    at NWWindow.<anonymous> (extensions::nw.Window:161:16)
```

**Comment by kiriles90** [comment]
Have you tried the latest dev builds from ci.popcorntime.app ? This was fixed long ago.

**Comment by Persei08** [comment]
Not related to fullscreen.
Duplicate of #1280 for which a workaround was released and is available on latest dev builds as @kiriles90 is saying
