### ISSUE TITLE
Compilation issue on VS code for Mac(M2 chip)

### ISSUE THREAD

**Issue by Dexter-Codes** [popcorntime/popcorntime#3028]
Unable to compile the latest code from Master branch. Any help is much appreciated here.
yarn run v1.22.22
$ gulp build
TypeError: (intermediate value).on is not a function
    at Object.<anonymous> (/Users/userx/development/popcorn-dev/popcorn-desktop/gulpfile.js:190:4)
    at Module._compile (node:internal/modules/cjs/loader:1358:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1416:10)
    at Module.load (node:internal/modules/cjs/loader:1208:32)
    at Module._load (node:internal/modules/cjs/loader:1024:12)
    at Module.require (node:internal/modules/cjs/loader:1233:19)
    at require (node:internal/modules/helpers:179:18)
    at requireOrImport (/Users/userx/development/popcorn-dev/popcorn-desktop/node_modules/gulp-cli/lib/shared/require-or-import.js:19:11)
    at execute (/Users/userx/development/popcorn-dev/popcorn-desktop/node_modules/gulp-cli/lib/versioned/^4.0.0/index.js:37:3)
    at Liftoff.handleArguments (/Users/userx/development/popcorn-dev/popcorn-desktop/node_modules/gulp-cli/index.js:211:24)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by merseyV** [comment]
If you just want a working copy - download the `Popcorn-Time-0.5.1-osxarm64.zip`

Stop torturing yourself? 😄

**Comment by merseyV** [comment]
If you just want a working copy - download the `Popcorn-Time-0.5.1-osxarm64.zip`

No need to flog a dead horse? 😄

**Comment by VenatusSimpleX** [comment]
I have the same issue but on Windows 10, may I know how this is completed and how I can build it please?

I'm having issues same as https://github.com/popcorn-official/popcorn-desktop/issues/2889 , and then after following https://github.com/popcorn-official/popcorn-desktop/issues/2889#issuecomment-2132448757 ,  this issue occured.
