### ISSUE TITLE
Error building on ArchLinux

### ISSUE THREAD

**Issue by ItachiSan** [popcorntime/popcorntime#337]
Operating System Version:

ArchLinux

Popcorn Time Version:

0.3.10

Download date:

Building it on ArchLinux, using the AUR package (see https://aur.archlinux.org/packages/popcorntime/, I am the official maintainer of the package)

#### Expected Behaviour

Building the package as expected.

#### Actual Behaviour

In order to build the package, I used to do `npm install` and then `gulp build`.
The `npm install` part works fine, but the `gulp build` breaks when starting the *nwjs* task.

#### Steps to reproduce the behaviour
When using the AUR package
1. `makepkg`
or else
1. `npm install`
2. `gulp build`

The error log is the following one:
```
[00:40:46] Using gulpfile ~/Packaging/popcorntime/src/popcorn-desktop-84a68ce66c6b8633a38563109ea49404e5b02dec/gulpfile.js
(node:16184) DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
[00:40:46] Starting 'build'...
[00:40:46] Starting 'injectgit'...
Branch: master
Commit: 5fd84a77
[00:40:46] Finished 'injectgit' after 249 ms
[00:40:46] Starting 'css'...
Stylus files compiled in /home/itachisan/Packaging/popcorntime/src/popcorn-desktop-84a68ce66c6b8633a38563109ea49404e5b02dec/src/app/themes/
[00:41:03] Finished 'css' after 17 s
[00:41:03] Starting 'nwjs'...
TypeError: Cannot read property 'filter' of undefined
    at /home/itachisan/Packaging/popcorntime/src/popcorn-desktop-84a68ce66c6b8633a38563109ea49404e5b02dec/node_modules/nw-builder/lib/versions.js:115:13
    at tryCatcher (/home/itachisan/Packaging/popcorntime/src/popcorn-desktop-84a68ce66c6b8633a38563109ea49404e5b02dec/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/itachisan/Packaging/popcorntime/src/popcorn-desktop-84a68ce66c6b8633a38563109ea49404e5b02dec/node_modules/bluebird/js/release/promise.js:510:31)
    at Promise._settlePromise (/home/itachisan/Packaging/popcorntime/src/popcorn-desktop-84a68ce66c6b8633a38563109ea49404e5b02dec/node_modules/bluebird/js/release/promise.js:567:18)
    at Promise._settlePromise0 (/home/itachisan/Packaging/popcorntime/src/popcorn-desktop-84a68ce66c6b8633a38563109ea49404e5b02dec/node_modules/bluebird/js/release/promise.js:612:10)
    at Promise._settlePromises (/home/itachisan/Packaging/popcorntime/src/popcorn-desktop-84a68ce66c6b8633a38563109ea49404e5b02dec/node_modules/bluebird/js/release/promise.js:691:18)
    at Async._drainQueue (/home/itachisan/Packaging/popcorntime/src/popcorn-desktop-84a68ce66c6b8633a38563109ea49404e5b02dec/node_modules/bluebird/js/release/async.js:138:16)
    at Async._drainQueues (/home/itachisan/Packaging/popcorntime/src/popcorn-desktop-84a68ce66c6b8633a38563109ea49404e5b02dec/node_modules/bluebird/js/release/async.js:148:10)
    at Immediate.Async.drainQueues (/home/itachisan/Packaging/popcorntime/src/popcorn-desktop-84a68ce66c6b8633a38563109ea49404e5b02dec/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:637:20)
    at tryOnImmediate (timers.js:610:5)
    at processImmediate [as _immediateCallback] (timers.js:582:5)
[00:43:34] Finished 'nwjs' after 2.5 min
[00:43:34] Finished 'build' after 2.8 min
```

**Comment by team-pct** [comment]
your issue seem to be with nw builder try rm -rf node_modules and npm i

**Comment by ItachiSan** [comment]
I did

```
cd $POPCORN_TIME_PATH
rm -rf $(npm config get cache)
rm -rf node_modules
nmp i
```

up to here is fine, no relevant log.
Then I do

```
gulp build
[16:37:25] Using gulpfile ~/Packaging/popcorntime/src/popcorn-desktop-84a68ce66c6b8633a38563109ea49404e5b02dec/gulpfile.js
(node:1235) DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
[16:37:25] Starting 'build'...
[16:37:25] Starting 'injectgit'...
Branch: master
Commit: 5fd84a77
[16:37:25] Finished 'injectgit' after 81 ms
[16:37:25] Starting 'css'...
Stylus files compiled in /home/itachisan/Packaging/popcorntime/src/popcorn-desktop-84a68ce66c6b8633a38563109ea49404e5b02dec/src/app/themes/
[16:37:41] Finished 'css' after 16 s
[16:37:41] Starting 'nwjs'...
TypeError: Cannot read property 'filter' of undefined
    at /home/itachisan/Packaging/popcorntime/src/popcorn-desktop-84a68ce66c6b8633a38563109ea49404e5b02dec/node_modules/nw-builder/lib/versions.js:115:13
    at tryCatcher (/home/itachisan/Packaging/popcorntime/src/popcorn-desktop-84a68ce66c6b8633a38563109ea49404e5b02dec/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/itachisan/Packaging/popcorntime/src/popcorn-desktop-84a68ce66c6b8633a38563109ea49404e5b02dec/node_modules/bluebird/js/release/promise.js:510:31)
    at Promise._settlePromise (/home/itachisan/Packaging/popcorntime/src/popcorn-desktop-84a68ce66c6b8633a38563109ea49404e5b02dec/node_modules/bluebird/js/release/promise.js:567:18)
    at Promise._settlePromise0 (/home/itachisan/Packaging/popcorntime/src/popcorn-desktop-84a68ce66c6b8633a38563109ea49404e5b02dec/node_modules/bluebird/js/release/promise.js:612:10)
    at Promise._settlePromises (/home/itachisan/Packaging/popcorntime/src/popcorn-desktop-84a68ce66c6b8633a38563109ea49404e5b02dec/node_modules/bluebird/js/release/promise.js:691:18)
    at Async._drainQueue (/home/itachisan/Packaging/popcorntime/src/popcorn-desktop-84a68ce66c6b8633a38563109ea49404e5b02dec/node_modules/bluebird/js/release/async.js:138:16)
    at Async._drainQueues (/home/itachisan/Packaging/popcorntime/src/popcorn-desktop-84a68ce66c6b8633a38563109ea49404e5b02dec/node_modules/bluebird/js/release/async.js:148:10)
    at Immediate.Async.drainQueues (/home/itachisan/Packaging/popcorntime/src/popcorn-desktop-84a68ce66c6b8633a38563109ea49404e5b02dec/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:637:20)
    at tryOnImmediate (timers.js:610:5)
    at processImmediate [as _immediateCallback] (timers.js:582:5)
[16:39:27] Finished 'nwjs' after 1.77 min
[16:39:27] Finished 'build' after 2.03 min
```

I sincerely don't know why _nw-builder_ fails.

**Comment by team-pct** [comment]
Have you tried with the updated nwjs-builder?

**Comment by ItachiSan** [comment]
Will try at home later today.

**Comment by ItachiSan** [comment]
Finally I was able to build the package, behind a VPN, with the updated nwjs-builder.
