### ISSUE TITLE
[DLNA] Is not working on Samsung KS8000

### ISSUE THREAD

**Issue by nando182** [popcorntime/popcorntime#342]
Operating System Version:
Windows 10 x64

Popcorn Time Version:
3.10

Download date:
11/14/2016

#### Expected Behaviour
Broadcast movies to my TV

#### Actual Behaviour
Nothing is being displayed on To

#### Steps to reproduce the behaviour
1. Open movie
2. Click on watch now and select my TV
3. The download start but nothing happens on TV

TV: Samsung KS8000

PT log:
 DLNA: play http://192.168.0.19:54248/ on '[TV] Samsung'
app.js:11 [INFO] DLNA: connecting to 192.168.0.18
app.js:11 [INFO] 20 subtitles found
app.js:21 [ERROR] DLNA.play error:  Error: Resource not found (716)
    at C:\Users\Fernando\AppData\Local\Popcorn-Time\node_modules\upnp-device-client\index.js:141:21
    at ConcatStream.<anonymous> (C:\Users\Fernando\AppData\Local\Popcorn-Time\node_modules\concat-stream\index.js:36:43)
    at emitNone (events.js:91:20)
    at ConcatStream.emit (events.js:185:7)
    at finishMaybe (C:\Users\Fernando\AppData\Local\Popcorn-Time\node_modules\readable-stream\lib\_stream_writable.js:475:14)
    at afterWrite (C:\Users\Fernando\AppData\Local\Popcorn-Time\node_modules\readable-stream\lib\_stream_writable.js:361:3)
    at _combinedTickCallback (internal/process/next_tick.js:80:20)
    at process._tickCallback (internal/process/next_tick.js:98:9)

**Comment by nando182** [comment]
@team-pct some idea?
