### ISSUE TITLE
Can't load subtitles from OpenSubtitles

### ISSUE THREAD

**Issue by urtzai** [popcorntime/popcorntime#363]
Which is the requisite to load subtitle from Opensubtiles? Why this sub does't appear in the subs menu?

http://www.opensubtitles.org/eu/subtitles/6803300/inside-out-eu

Do I need some configuration in order to appear in the application? 

Thank you

Operating System Version:
Linux Ubuntu 16.10 64-bit

Popcorn Time Version:
Popcorn-time 3.10

**Comment by team-pct** [comment]
F12 and send us the logs

**Comment by urtzai** [comment]
Hi! This is the error log. Then, I try to load manually from custom subs option, and works fine:

```
Database path: /home/urtzai/.config/Popcorn-Time/Default
[INFO] Scanning: Local Network for Airplay devices
[INFO] Scanning: Local Network for DLNA devices
[INFO] Scanning: Local Network for Chromecast devices
[INFO] Scanning: /usr/bin
[INFO] Scanning: /usr/local/bin
loading npm /butter-settings-/ butter-settings-popcorntime.io
loading local provider cache_provider.js
loading local provider cache_providerv2.js
loading local provider favorites.js
loading local provider opensubtitles.js
loading local provider torrent_cache.js
loading local provider trakttv.js
loading local provider tvshowtime.js
loading local provider watchlist.js
loading npm /butter-provider-/ butter-provider-movies
added MovieApi to provider registry
loading npm /butter-provider-/ butter-provider-tvapi
added TVApi to provider registry
loading npm /butter-provider-/ butter-provider-anime
added AnimeApi to provider registry
loading npm /butter-provider-/ butter-provider-vodo
added vodo to provider registry
[INFO] Found External Player: VLC in /usr/bin
[INFO] External Players: scan finished
[INFO] Loading DB
loaded cache_provider.js
loaded cache_providerv2.js
added Favorites to provider registry
loaded favorites.js
added OpenSubtitles to provider registry
loaded opensubtitles.js
added TorrentCache to provider registry
loaded torrent_cache.js
added Trakttv to provider registry
loaded trakttv.js
added TVShowTime to provider registry
loaded tvshowtime.js
added Watchlist to provider registry
loaded watchlist.js
[INFO] Spawning new provider MovieApi?&apiURL=https://movies-v2.api-fetch.website/,cloudflare+https://movies-v2.api-fetch.website, Object
[INFO] Spawning new provider TVApi?&apiURL=https://tv-v2.api-fetch.website/,cloudflare+https://tv-v2.api-fetch.website, Object
[INFO] Spawning new provider AnimeApi?&apiURL=https://anime.api-fetch.website/,cloudflare+https://anime.api-fetch.website, Object
[INFO] Spawning new provider vodo Object
[INFO] Spawning new provider OpenSubtitles Object
[INFO] Spawning new provider Trakttv Object
[INFO] Spawning new provider TVShowTime Object
[INFO] Spawning new provider TorrentCache Object
loaded Array[8]
[INFO] Initializing HTTP API server
[INFO] Returning cached provider Trakttv
[INFO] Returning cached provider TVShowTime
[INFO] Returning cached provider MovieApi?&apiURL=https://movies-v2.api-fetch.website/,cloudflare+https://movies-v2.api-fetch.website,
pre--- undefined undefined Array[1]
pre all Array[3]
[INFO] Returning cached provider MovieApi?&apiURL=https://movies-v2.api-fetch.website/,cloudflare+https://movies-v2.api-fetch.website,
[INFO] Returning cached provider TVApi?&apiURL=https://tv-v2.api-fetch.website/,cloudflare+https://tv-v2.api-fetch.website,
[INFO] Returning cached provider AnimeApi?&apiURL=https://anime.api-fetch.website/,cloudflare+https://anime.api-fetch.website,
[INFO] Returning cached provider vodo
[DEBUG] Butter 0.3.10 startup time: 1863.600ms
post all Object true true
[DEBUG] Not updating because we are running the latest version
[INFO] Returning cached provider MovieApi?&apiURL=https://movies-v2.api-fetch.website/,cloudflare+https://movies-v2.api-fetch.website,
pre--- undefined undefined [MovieApi]
pre all [Promise, true, true]
post all Object {results: Array[1], hasMore: true} true true
[INFO] Returning cached provider MovieApi?&apiURL=https://movies-v2.api-fetch.website/,cloudflare+https://movies-v2.api-fetch.website,
Object {type: "movie", imdb_id: "tt2096673", title: "Inside Out", year: "2015", genre: Array[3]…} "Movie"
[INFO] Show movie detail (tt2096673)
[INFO] Subtitles: none
pre--- undefined undefined [MovieApi]
pre all [Promise, true, true]
post all Object {results: Array[0], hasMore: true} true true
[INFO] Loading torrent
[DEBUG] Subtitles data request: Object {type: "movie", imdbid: "tt2096673", filename: undefined, keywords: Array[0]}
[INFO] Returning cached provider OpenSubtitles
[DEBUG] Streaming movie to /tmp/Butter/4b3dce31c713b02726f67e2ef49de9ff965ec3b7
[INFO] Loading torrent: startingDownload
[INFO] 38 subtitles found
Subtitle download url: http://dl.opensubtitles.org/en/download/src-api/vrf-19d40c5f/sid-25iKvdKcInLQiwZIbE75zNM1pR6/filead/1955383497
SUB charset detected:  UTF-8
[DEBUG] SubtitleServer: loading /tmp/Butter/4b3dce31c713b02726f67e2ef49de9ff965ec3b7/Inside Out (2015)/Inside.Out.2015.720p.BluRay.x264.YIFY.srt
[INFO] Loading torrent: downloading
[INFO] Loading torrent: ready
[INFO] Watching: Inside Out
[DEBUG] SUB charset detected: UTF-8
[ERROR] Error reading subtitles timing, file seems corrupted TypeError: Cannot read property 'split' of undefined
    at subObj.vjs.TextTrack.parseCueTime (chrome-extension://hecfofbbdfadifpemejbbdcjmfmboohj/src/app/vendor/video.js/dist/video-js/video.dev.js:8291:16)
    at subObj.vjs.TextTrack.parseCues (chrome-extension://hecfofbbdfadifpemejbbdcjmfmboohj/src/app/vendor/video.js/dist/video-js/video.dev.js:8248:28)
    at vjsBind (chrome-extension://hecfofbbdfadifpemejbbdcjmfmboohj/src/app/vendor/videojshooks.js:323:23)
    at parse (chrome-extension://hecfofbbdfadifpemejbbdcjmfmboohj/src/app/vendor/videojshooks.js:288:17)
    at decode (chrome-extension://hecfofbbdfadifpemejbbdcjmfmboohj/src/app/vendor/videojshooks.js:296:17)
    at chrome-extension://hecfofbbdfadifpemejbbdcjmfmboohj/src/app/vendor/videojshooks.js:353:17
    at Request._callback (chrome-extension://hecfofbbdfadifpemejbbdcjmfmboohj/src/app/vendor/videojshooks.js:129:25)
[DEBUG] Resuming position to 94 secs
[DEBUG] SUB charset detected: UTF-8
[INFO] Subtitles loaded!
```

**Comment by Persei08** [comment]
Is Basque language supported for subtitles? Basque language is a regional language mainly spoken in Spain and France.

**Comment by urtzai** [comment]
Yes it is... 'eu', 'Euskara' (native name) is set in the language config: https://github.com/popcorn-official/popcorn-desktop/blob/development/src/app/language.js

The problem is that at the beginning subtitles loading process crashes, but if you stop and continue playing subs appear...

**Comment by urtzai** [comment]
Ok I think the problem is the subs timing... And I was confused because in the android app I have the same problem. I mean, basque subs don't appear. But that is another issue.

Thank you
