### ISSUE TITLE
[development branch] ES6 syntax incompatibility for Node v0.10 and v0.12

### ISSUE THREAD

**Issue by richardwu** [popcorntime/popcorntime#408]
Operating System:
OS X 10.11.6

Popcorn Time Version:
54.0.2840.99

Node version:
v0.12.7

Download date:
December 21, 2016

#### Expected Behaviour
Build and install from the script make_popcorn.sh

#### Actual Behaviour
Syntax error raised when script was building with `gulp build`.

```
/Users/<redacted>/<redacted>/popcorn-desktop/gulpfile.js:6
const nwVersion = '0.18.6',
^^^^^
SyntaxError: Use of const in strict mode.
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at execute (/usr/local/lib/node_modules/gulp-cli/lib/versioned/^3.7.0/index.js:24:18)
    at Liftoff.handleArguments (/usr/local/lib/node_modules/gulp-cli/index.js:149:63)
    at Liftoff.<anonymous> (/usr/local/lib/node_modules/gulp-cli/node_modules/liftoff/index.js:198:16)
```

#### Steps to reproduce the behaviour
1. Clone the development branch
2. Run `./make_popcorn.sh`

**Comment by richardwu** [comment]
This was resolved by adding the `--harmony` flag to `gulp build` and `gulp run`.

**Comment by sumitsrv** [comment]
I am getting another build error when using "harmony". 

`butter-desktop/gulpfile.js:39
const parsePlatforms = () => {
                        ^
SyntaxError: Unexpected token )
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at execute (/usr/lib/node_modules/gulp-cli/lib/versioned/^3.7.0/index.js:24:18)
    at Liftoff.handleArguments (/usr/lib/node_modules/gulp-cli/index.js:149:63)
    at Liftoff.<anonymous> (/usr/lib/node_modules/gulp-cli/node_modules/liftoff/index.js:198:16)
    at module.exports (/usr/lib/node_modules/gulp-cli/node_modules/liftoff/node_modules/flagged-respawn/index.js:17:3)`
