### ISSUE TITLE
Not able to run locally [osx64 is not available in cache]

### ISSUE THREAD

**Issue by Ajeey** [popcorntime/popcorntime#450]
Operating System Version:
OS X - 10.10

Steps I followed to build - 

- git clone
- npm install
- bower install
- gulp build
- gulp run

And during "gulp run" I am getting into this error - 
```
[16:13:18] Starting 'run'...
Running osx64 from cache
osx64 is not available in cache. Try running `gulp build` beforehand
[16:13:18] 'run' errored after 7.2 ms
[16:13:18] Error: spawn cache/0.18.6-sdk/osx64/nwjs.app/Contents/MacOS/nwjs ENOENT
    at exports._errnoException (util.js:870:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at doNTCallback2 (node.js:441:9)
    at process._tickCallback (node.js:355:17)
    at Function.Module.runMain (module.js:469:11)
    at startup (node.js:136:18)
    at node.js:963:3
Popcorn-Time exited with code -2
```

**Comment by ChrisAlderson** [comment]
See if the `cache/0.18.6-sdk/osx64/nwjs.app/Contents/MacOS/nwjs` file/folder exists. `ENOENT` means the file or folder does not exists.

**Comment by hodrigohamalho** [comment]
same error here...

**Comment by kartikv11** [comment]
`gulp build` should create the required `cache/..` dir in your repository, post which you can do `gulp run`
