### ISSUE TITLE
Cannot build latest version 

### ISSUE THREAD

**Issue by vRITHNER** [popcorntime/popcorntime#497]
Operating System Version:
Windows 10

Popcorn Time Version:
0.3.10.0 beta

Download date:
Today for last time

#### Expected Behaviour
I followed each step to compile and run latest dev version
I expect to have run correctly
...

#### Actual Behaviour
I followed each step to compile and run latest dev version
during gulp build I got an error
"
```
[18:52:15] Starting 'nwjs'...
{ Error: Command failed: npm ls --production=true --parseable=true
npm ERR! missing: TorrentCollection@^x.x.x, required by Popcorn-Time@0.3.10

    at ChildProcess.exithandler (child_process.js:202:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:852:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
  killed: false,
  code: 1,
  signal: null,
  cmd: 'npm ls --production=true --parseable=true' }
"
```

#### Steps to reproduce the behaviour
1. git clone
2. npm install -g bower gulp (Linux: you may need to run with sudo)
3. npm install
4. bower install
5. gulp build

fyi: I tried to install TorrentCollection package but I get also an error:

```
D:\MediaTools\popcorn-desktop\node_modules\canvas>if not defined npm_config_node_gyp (node "C:\Program Files (x86)\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
Warning: Missing input files:
C:\GTK\bin\zlib1.dll
C:\GTK\bin\libexpat-1.dll
C:\GTK\bin\libpng14-14.dll
C:\GTK\bin\libcairo-2.dll
C:\GTK\bin\libfontconfig-1.dll
C:\GTK\bin\libfreetype-6.dll
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  Canvas.cc
  CanvasGradient.cc
  CanvasPattern.cc
  CanvasRenderingContext2d.cc
  color.cc
  Image.cc
  ImageData.cc
  init.cc
d:\mediatools\popcorn-desktop\node_modules\canvas\src\Canvas.h(19): fatal error C1083: Cannot open include file: 'cairo.h': No such file or directory (compiling source file ..\src
\Image.cc) [D:\MediaTools\popcorn-desktop\node_modules\canvas\build\canvas.vcxproj]
d:\mediatools\popcorn-desktop\node_modules\canvas\src\Canvas.h(19): fatal error C1083: Cannot open include file: 'cairo.h': No such file or directory (compiling source file ..\src
\CanvasPattern.cc) [D:\MediaTools\popcorn-desktop\node_modules\canvas\build\canvas.vcxproj]
d:\mediatools\popcorn-desktop\node_modules\canvas\src\Canvas.h(19): fatal error C1083: Cannot open include file: 'cairo.h': No such file or directory (compiling source file ..\src
\Canvas.cc) [D:\MediaTools\popcorn-desktop\node_modules\canvas\build\canvas.vcxproj]
d:\mediatools\popcorn-desktop\node_modules\canvas\src\Canvas.h(19): fatal error C1083: Cannot open include file: 'cairo.h': No such file or directory (compiling source file ..\src
\init.cc) [D:\MediaTools\popcorn-desktop\node_modules\canvas\build\canvas.vcxproj]
d:\mediatools\popcorn-desktop\node_modules\canvas\src\Canvas.h(19): fatal error C1083: Cannot open include file: 'cairo.h': No such file or directory (compiling source file ..\src
\CanvasGradient.cc) [D:\MediaTools\popcorn-desktop\node_modules\canvas\build\canvas.vcxproj]
d:\mediatools\popcorn-desktop\node_modules\canvas\src\Canvas.h(19): fatal error C1083: Cannot open include file: 'cairo.h': No such file or directory (compiling source file ..\src
\ImageData.cc) [D:\MediaTools\popcorn-desktop\node_modules\canvas\build\canvas.vcxproj]
d:\mediatools\popcorn-desktop\node_modules\canvas\src\Canvas.h(19): fatal error C1083: Cannot open include file: 'cairo.h': No such file or directory (compiling source file ..\src
\CanvasRenderingContext2d.cc) [D:\MediaTools\popcorn-desktop\node_modules\canvas\build\canvas.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `msbuild` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
gyp ERR! System Windows_NT 10.0.15046
gyp ERR! command "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd D:\MediaTools\popcorn-desktop\node_modules\canvas
gyp ERR! node -v v6.3.1
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok
Popcorn-Time@0.3.10 D:\MediaTools\popcorn-desktop
`-- (empty)

npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.1.1
npm ERR! Windows_NT 10.0.15046
npm ERR! argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "i" "Torrentcollection"
npm ERR! node v6.3.1
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE

npm ERR! canvas@1.6.4 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the canvas@1.6.4 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the canvas package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs canvas
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls canvas
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\MediaTools\popcorn-desktop\npm-debug.log

```
```


Txs

**Comment by mrexodia** [comment]
My pull request #498 explains how to solve this issue.

> If you are on Windows, follow [this guide](https://github.com/Automattic/node-canvas/wiki/Installation---Windows) to properly install `node-canvas`. If you get errors related to `gulp` not being found, check out [this answer](http://stackoverflow.com/a/24042936).

**Comment by vRITHNER** [comment]
Hi an txs for your support:

d:\MediaTools\popcorn-desktop>npm install  --GTK_Root=d:\MediaTools\Gtk

 

> canvas@1.6.4 install d:\MediaTools\popcorn-desktop\node_modules\canvas

> node-gyp rebuild

 

 

d:\MediaTools\popcorn-desktop\node_modules\canvas>if not defined npm_config_node_gyp (node "C:\Program Files (x86)\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )

Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.

  Canvas.cc

  CanvasGradient.cc

  CanvasPattern.cc

  CanvasRenderingContext2d.cc

  color.cc

  Image.cc

  ImageData.cc

  init.cc

..\src\CanvasRenderingContext2d.cc(801): warning C4458: declaration of 'constructor' hides class member [d:\MediaTools\popcorn-desktop\node_modules\canvas\build\canvas.vcxproj]

  d:\mediatools\popcorn-desktop\node_modules\canvas\src\CanvasRenderingContext2d.h(72): note: see declaration of 'Context2d::constructor' (compiling source file ..\src\CanvasRende

  ringContext2d.cc)

..\src\Canvas.cc(154): warning C4457: declaration of 'data' hides function parameter [d:\MediaTools\popcorn-desktop\node_modules\canvas\build\canvas.vcxproj]

  ..\src\Canvas.cc(150): note: see declaration of 'data'

  win_delay_load_hook.c

C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\node-gyp\src\win_delay_load_hook.c(31): warning C4055: 'type cast': from data pointer 'HMODULE' to function pointer 'FA

RPROC' [d:\MediaTools\popcorn-desktop\node_modules\canvas\build\canvas.vcxproj]

C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\node-gyp\src\win_delay_load_hook.c(34): error C2373: '__pfnDliNotifyHook2': redefinition; different type modifiers [d:\

MediaTools\popcorn-desktop\node_modules\canvas\build\canvas.vcxproj]
