### ISSUE TITLE
Cant set up custom subtitles

### ISSUE THREAD

**Issue by blackshot** [popcorntime/popcorntime#516]
Operating System Version:
Windows 10

Popcorn Time Version:
Latest build from jenkins x64
https://ci.popcorntime.sh/job/Popcorn-Time-Desktop/245/

Download date:
Today, i updated it like 20 minutes ago.

#### Expected Behaviour
Load subtitles from .srt file

#### Actual Behaviour
nothing

steps: let pass some minutes of the video, and try to set up subtitles
also. console output.

`[INFO] Loading torrent: ready
app.js:11 [INFO] Watching: Marvel's Iron Fist - Temporada 1, Episodio 1 - Snow Gives Way
app.js:6 [DEBUG] Player - data loaded in 57ms
app.js:6 [DEBUG] Resuming position to 525 secs
video.dev.js:1409 VIDEOJS: Video.js: currentTime unavailable on Html5 playback technology element. TypeError: Cannot read property 'currentTime' of null(…)
video.dev.js:4239 Uncaught TypeError: Cannot read property 'currentTime' of null(…)
app.js:21 [ERROR] TypeError: Cannot read property 'currentTime' of null TypeError: Cannot read property 'currentTime' of null
    at subObj.vjs.Html5.currentTime (chrome-extension://hecfofbbdfadifpemejbbdcjmfmboohj/src/app/vendor/video.js/dist/video-js/video.dev.js:6905:62)
    at subObj.vjs.Player.techGet (chrome-extension://hecfofbbdfadifpemejbbdcjmfmboohj/src/app/vendor/video.js/dist/video-js/video.dev.js:4225:31)
    at subObj.vjs.Player.currentTime (chrome-extension://hecfofbbdfadifpemejbbdcjmfmboohj/src/app/vendor/video.js/dist/video-js/video.dev.js:4310:42)
    at c.<anonymous> (chrome-extension://hecfofbbdfadifpemejbbdcjmfmboohj/src/app/lib/views/player/player.js:441:43)
    at _ (chrome-extension://hecfofbbdfadifpemejbbdcjmfmboohj/src/app/vendor/backbone/backbone-min.js:1:3942)
    at m (chrome-extension://hecfofbbdfadifpemejbbdcjmfmboohj/src/app/vendor/backbone/backbone-min.js:1:3728)
    at f (chrome-extension://hecfofbbdfadifpemejbbdcjmfmboohj/src/app/vendor/backbone/backbone-min.js:1:1563)
    at c.l.trigger (chrome-extension://hecfofbbdfadifpemejbbdcjmfmboohj/src/app/vendor/backbone/backbone-min.js:1:3608)
    at subObj.CustomTrackMenuItem.loadSubtitle (chrome-extension://hecfofbbdfadifpemejbbdcjmfmboohj/src/app/vendor/videojsplugins.js:152:18)
    at HTMLInputElement.<anonymous> (chrome-extension://hecfofbbdfadifpemejbbdcjmfmboohj/src/app/vendor/videojsplugins.js:124:22)win.error @ app.js:21`

the only way i troubleshooted this, is restarting the the whole client

**Comment by streger** [comment]
Try with latest version from ci to reproduce this and report.
