### ISSUE TITLE
Timeout issue on console.

### ISSUE THREAD

**Issue by Abhinav1217** [popcorntime/popcorntime#542]
**Operating System Version:**

Linux Fedora 25.
**Popcorn Time Version:**

0.3.10-0 "Popcorn is Love" Beta - HEAD (28112f67) 
**Download date:**

About 3 months ago. I checked for update on https://popcorntime.sh/ before submitting issue here.  

**Expected Behaviour**

...
Everything should work smoothly.
#### Actual Behaviour

...
About a month ago, download were starting late, They would stop randomly during playing. 
I checked the F12 console, and I am getting timeout error as follows
```
143app.js:21 [ERROR] TypeError: Cannot read property 'timeout' of undefined TypeError: Cannot read property 'timeout' of undefined
    at /opt/popcorn-time/node_modules/torrent-tracker/index.js:132:62
    at doSend (dgram.js:374:7)
    at afterDns (dgram.js:366:5)
    at GetAddrInfoReqWrap.asyncCallback [as callback] (dns.js:62:16)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:76:17)win.error @ app.js:21(anonymous function) @ app.js:699emitOne @ events.js:96emit @ events.js:188process._fatalException @ bootstrap_node.js:313
app.js:16 [WARNING] No subtitles returnedwin.warn @ app.js:16(anonymous function) @ streamer.js:247tryCatcher @ /opt/popcorn-time/node_modules/bluebird/js/release/util.js:16Promise._settlePromiseFromHandler @ /opt/popcorn-time/node_modules/bluebird/js/release/promise.js:510Promise._settlePromise @ /opt/popcorn-time/node_modules/bluebird/js/release/promise.js:567Promise._settlePromise0 @ /opt/popcorn-time/node_modules/bluebird/js/release/promise.js:612Promise._settlePromises @ /opt/popcorn-time/node_modules/bluebird/js/release/promise.js:691Promise._fulfill @ /opt/popcorn-time/node_modules/bluebird/js/release/promise.js:636Promise._resolveCallback @ /opt/popcorn-time/node_modules/bluebird/js/release/promise.js:431Promise._settlePromiseFromHandler @ /opt/popcorn-time/node_modules/bluebird/js/release/promise.js:522Promise._settlePromise @ /opt/popcorn-time/node_modules/bluebird/js/release/promise.js:567Promise._settlePromise0 @ /opt/popcorn-time/node_modules/bluebird/js/release/promise.js:612Promise._settlePromises @ /opt/popcorn-time/node_modules/bluebird/js/release/promise.js:691Promise._fulfill @ /opt/popcorn-time/node_modules/bluebird/js/release/promise.js:636Promise._resolveCallback @ /opt/popcorn-time/node_modules/bluebird/js/release/promise.js:453Promise._settlePromiseFromHandler @ /opt/popcorn-time/node_modules/bluebird/js/release/promise.js:522Promise._settlePromise @ /opt/popcorn-time/node_modules/bluebird/js/release/promise.js:567Promise._settlePromise0 @ /opt/popcorn-time/node_modules/bluebird/js/release/promise.js:612Promise._settlePromises @ /opt/popcorn-time/node_modules/bluebird/js/release/promise.js:691Promise._fulfill @ /opt/popcorn-time/node_modules/bluebird/js/release/promise.js:636Promise._resolveCallback @ /opt/popcorn-time/node_modules/bluebird/js/release/promise.js:453Promise._settlePromiseFromHandler @ /opt/popcorn-time/node_modules/bluebird/js/release/promise.js:522Promise._settlePromise @ /opt/popcorn-time/node_modules/bluebird/js/release/promise.js:567Promise._settlePromise0 @ /opt/popcorn-time/node_modules/bluebird/js/release/promise.js:612Promise._settlePromises @ /opt/popcorn-time/node_modules/bluebird/js/release/promise.js:691Promise._fulfill @ /opt/popcorn-time/node_modules/bluebird/js/release/promise.js:636Promise._resolveCallback @ /opt/popcorn-time/node_modules/bluebird/js/release/promise.js:453Promise._settlePromiseFromHandler @ /opt/popcorn-time/node_modules/bluebird/js/release/promise.js:522Promise._settlePromise @ /opt/popcorn-time/node_modules/bluebird/js/release/promise.js:567Promise._settlePromise0 @ /opt/popcorn-time/node_modules/bluebird/js/release/promise.js:612Promise._settlePromises @ /opt/popcorn-time/node_modules/bluebird/js/release/promise.js:691Promise._fulfill @ /opt/popcorn-time/node_modules/bluebird/js/release/promise.js:636Promise._resolveCallback @ /opt/popcorn-time/node_modules/bluebird/js/release/promise.js:431ReductionPromiseArray._resolve @ /opt/popcorn-time/node_modules/bluebird/js/release/reduce.js:61completed @ /opt/popcorn-time/node_modules/bluebird/js/release/reduce.js:122Promise._settlePromise @ /opt/popcorn-time/node_modules/bluebird/js/release/promise.js:564Promise._settlePromise0 @ /opt/popcorn-time/node_modules/bluebird/js/release/promise.js:612Promise._settlePromises @ /opt/popcorn-time/node_modules/bluebird/js/release/promise.js:691Async._drainQueue @ /opt/popcorn-time/node_modules/bluebird/js/release/async.js:138Async._drainQueues @ /opt/popcorn-time/node_modules/bluebird/js/release/async.js:148Async.drainQueues @ /opt/popcorn-time/node_modules/bluebird/js/release/async.js:17_tickCallback @ internal/process/next_tick.js:103
```

Here is a screenshot, as you can see there are over 500 and counting errors. all are the same one i pasted above.
![screenshot from 2017-05-18 12-10-19](https://cloud.githubusercontent.com/assets/740584/26189633/1c324b02-3b95-11e7-9da6-0519eb9d5e21.png)

Earlier, This error only show a few times, But for past few days, This error is logged even if I just keep popcorn time open and do nothing on it. It is delaying the start of downloading and moreover, Today It kept hanging the playback even though that portion of video was downloaded.

I tried with VPN also, same result.

**Comment by streger** [comment]
It seems that you have a problem with downloading subtitles or with screening it to local sever on tv. This will be looked at even though your system is pretty unique since you're using Fedora.

**Comment by Abhinav1217** [comment]
I am not screening it to local server. I only run it on laptop.  Error log for  subtitle not found is different than this error. 

When subtitle is not found then It shows a warning "the yellow line" on app.js line 16 
Here is the screenshot of the Subtitle not found. Hope it helps.
![screenshot from 2017-05-24 15-07-26](https://cloud.githubusercontent.com/assets/740584/26397161/e4f66568-4064-11e7-916f-0445ae4aa9f2.png)

In past when my internet plan was slow, I did used to get this problem when working with low seeds. But error count never went this high. But now, above screenshot is of a latest torrent with lots of seeds and my internet plan is also 4mbps. 

By a long shot guess, does this have to do updating chromium or node?  Fedora is known to be a more bleeding edge compared to ubuntu. Although, I won't call my system unique ;)
