### ISSUE TITLE
Time and top bar keep showing up.

### ISSUE THREAD

**Issue by sergitvd** [popcorntime/popcorntime#546]
Operating System Version:
Windows 10

Popcorn Time Version:
3.10

Download date:
A couple of months ago

#### Expected Behaviour
When I enter fullscreen, mouse and time bar should dissappear until I move it.

#### Actual Behaviour
The time bar keeps showing up as if I moved the mouse using the internal player only (tried disconnecting the mouse just in case and kept happening).

#### Steps to reproduce the behaviour

1. Select movie.
2. Enter fullscreen.

**Comment by streger** [comment]
Please make a video of this, and copy/paste the log output here from the console log after you click F12 on your keyboard in PT.

Do freely mask the video you were looking at.

**Comment by sergitvd** [comment]
Here's the video: [2017-05-24 08-27-35.zip](https://github.com/popcorn-official/popcorn-desktop/files/1024635/2017-05-24.08-27-35.zip)

`video.dev.js:928 Uncaught TypeError: Cannot read property 'vdata1495608217327' of null(…)vjs.hasData @ video.dev.js:928vjs.trigger @ video.dev.js:574vjs.Component.trigger @ video.dev.js:2412(anonymous function) @ video.dev.js:4575ret @ video.dev.js:868data.dispatcher @ video.dev.js:343
app.js:21 [ERROR] TypeError: Cannot read property 'vdata1495608217327' of null TypeError: Cannot read property 'vdata1495608217327' of null
    at Function.vjs.hasData (chrome-extension://hecfofbbdfadifpemejbbdcjmfmboohj/src/app/vendor/video.js/dist/video-js/video.dev.js:928:14)
    at Function.vjs.trigger (chrome-extension://hecfofbbdfadifpemejbbdcjmfmboohj/src/app/vendor/video.js/dist/video-js/video.dev.js:574:23)
    at subObj.vjs.Component.trigger (chrome-extension://hecfofbbdfadifpemejbbdcjmfmboohj/src/app/vendor/video.js/dist/video-js/video.dev.js:2412:7)
    at subObj.<anonymous> (chrome-extension://hecfofbbdfadifpemejbbdcjmfmboohj/src/app/vendor/video.js/dist/video-js/video.dev.js:4575:12)
    at HTMLDocument.ret (chrome-extension://hecfofbbdfadifpemejbbdcjmfmboohj/src/app/vendor/video.js/dist/video-js/video.dev.js:868:15)
    at HTMLDocument.data.dispatcher (chrome-extension://hecfofbbdfadifpemejbbdcjmfmboohj/src/app/vendor/video.js/dist/video-js/video.dev.js:343:29)win.error @ app.js:21(anonymous function) @ app.js:699emitOne @ events.js:96emit @ events.js:188process._fatalException @ bootstrap_node.js:313`



Didn't know how to make the code look beter so I also attach a screenshot of the log.
![sketch 3](https://cloud.githubusercontent.com/assets/28902796/26390508/1fece6b6-405f-11e7-865c-d3bf56598394.png)

I hope everything is as you needed, if I did anything wrong I'll redo it. Thanks!

**Comment by sergitvd** [comment]
I tried to replicate the log again to make sure I did it right but never got the same errors again whilst the problem persisted. It's because I closed the player I guessed, before that there were 0 errors.

**Comment by GKid94** [comment]
It happens to me too, it's so irritating 😕😤

**Comment by ChrisAlderson** [comment]
Use the search function people #535
