### ISSUE TITLE
Gulp dist failling

### ISSUE THREAD

**Issue by Persei08** [popcorntime/popcorntime#753]
Operating System Version:
Ubuntu 16.04 64bits

Popcorn Time Version:
development  branch
Download date:
2018-04-12
#### Expected Behaviour
Create redistribuable packages
...

#### Actual Behaviour
It fail at 'compress' task.

Here the console output ( don't worry about ~/dev/butter/butter-desktop/ path, this is popcorntime development branch):
```
persei@persei-ubu:~/dev/butter/butter-desktop (popcorn-development $=) $ gulp dist --platform=all
[15:58:16] Using gulpfile ~/dev/butter/butter-desktop/gulpfile.js
[15:58:16] Starting 'dist'...
[15:58:16] Starting 'build'...
[15:58:16] Starting 'injectgit'...
Branch: popcorn-development
Commit: f3135466
[15:58:16] Finished 'injectgit' after 40 ms
[15:58:16] Starting 'css'...
Stylus files compiled in /home/persei/dev/butter/butter-desktop/src/app/themes/
[15:58:22] Finished 'css' after 6.06 s
[15:58:22] Starting 'nwjs'...
Using v0.18.6 (sdk)
Create cache folder in /home/persei/dev/butter/butter-desktop/cache/0.18.6-sdk
Using cache for: linux64
Create release folder in /home/persei/dev/butter/butter-desktop/build/Popcorn-Time/linux64
[16:01:35] Finished 'nwjs' after 3.22 min
[16:01:35] Finished 'build' after 3.32 min
[16:01:35] Starting 'compress'...
Packaging tar for: linux64
[16:01:35] 'compress' errored after 175 ms
[16:01:35] TypeError: handler.state is not a function
    at Object.inspect (/home/persei/dev/butter/butter-desktop/node_modules/when/lib/state.js:28:23)
    at formatValue (util.js:369:36)
    at formatProperty (util.js:822:15)
    at util.js:681:12
    at Array.map (native)
    at formatObject (util.js:680:15)
    at formatValue (util.js:620:16)
    at formatProperty (util.js:822:15)
    at util.js:681:12
    at Array.map (native)
[16:01:35] 'dist' errored after 3.32 min
[16:01:35] TypeError in plugin "run-sequence(compress)"
Message:
    handler.state is not a function
Stack:
TypeError: handler.state is not a function
    at Object.inspect (/home/persei/dev/butter/butter-desktop/node_modules/when/lib/state.js:28:23)
    at formatValue (util.js:369:36)
    at formatProperty (util.js:822:15)
    at util.js:681:12
    at Array.map (native)
    at formatObject (util.js:680:15)
    at formatValue (util.js:620:16)
    at formatProperty (util.js:822:15)
    at util.js:681:12
    at Array.map (native)
```

#### Steps to reproduce the behaviour

1. `sudo npm install -g bower gulp`
2. `bower install`
3. `sudo npm install`
4. `gulp build`
5. `gulp dist --platform=all`

**Comment by Persei08** [comment]
Ok, forgive me, it seem to work after reboot

**Comment by Persei08** [comment]
Ok, finally it come back. 
In the example (console output) above, the parameter was wrong so it was generating the package for linux64 only.

But finally relaunching it with `plateforms=all` it failed at the compress task of osx64 plateform.

```
persei@persei-ubu:~/dev/butter/butter-desktop (popcorn-development *$=) $ gulp dist --platforms=all
[11:42:32] Using gulpfile ~/dev/butter/butter-desktop/gulpfile.js
[11:42:32] Starting 'dist'...
[11:42:32] Starting 'build'...
[11:42:32] Starting 'injectgit'...
Branch: popcorn-development
Commit: f3135466
[11:42:32] Finished 'injectgit' after 32 ms
[11:42:32] Starting 'css'...
Stylus files compiled in /home/persei/dev/butter/butter-desktop/src/app/themes/
[11:42:38] Finished 'css' after 6.05 s
[11:42:38] Starting 'nwjs'...
Using v0.18.6 (sdk)
Create cache folder in /home/persei/dev/butter/butter-desktop/cache/0.18.6-sdk
Downloading: https://get.popcorntime.sh/repo/nw/v0.18.6/nwjs-sdk-v0.18.6-win-ia32.zip
Create cache folder in /home/persei/dev/butter/butter-desktop/cache/0.18.6-sdk
Downloading: https://get.popcorntime.sh/repo/nw/v0.18.6/nwjs-sdk-v0.18.6-win-x64.zip
Create cache folder in /home/persei/dev/butter/butter-desktop/cache/0.18.6-sdk
Downloading: https://get.popcorntime.sh/repo/nw/v0.18.6/nwjs-sdk-v0.18.6-osx-x64.zip
Create cache folder in /home/persei/dev/butter/butter-desktop/cache/0.18.6-sdk
Downloading: https://get.popcorntime.sh/repo/nw/v0.18.6/nwjs-sdk-v0.18.6-linux-ia32.tar.gz
Create cache folder in /home/persei/dev/butter/butter-desktop/cache/0.18.6-sdk
Using cache for: linux64
  downloading [====================] 100% 0.0s

Create release folder in /home/persei/dev/butter/butter-desktop/build/Popcorn-Time/win64
Create release folder in /home/persei/dev/butter/butter-desktop/build/Popcorn-Time/win32
Create release folder in /home/persei/dev/butter/butter-desktop/build/Popcorn-Time/linux32
Create release folder in /home/persei/dev/butter/butter-desktop/build/Popcorn-Time/osx64
Create release folder in /home/persei/dev/butter/butter-desktop/build/Popcorn-Time/linux64
[12:07:27] Finished 'nwjs' after 25 min
[12:07:27] Finished 'build' after 25 min
[12:07:27] Starting 'compress'...
Packaging tar for: linux32
Packaging tar for: linux64
No `compress` task for: win32
No `compress` task for: win64
Packaging tar for: osx64
[12:07:27] 'compress' errored after 244 ms
[12:07:27] TypeError: handler.state is not a function
    at Object.inspect (/home/persei/dev/butter/butter-desktop/node_modules/when/lib/state.js:28:23)
    at formatValue (util.js:369:36)
    at formatProperty (util.js:822:15)
    at util.js:681:12
    at Array.map (native)
    at formatObject (util.js:680:15)
    at formatValue (util.js:620:16)
    at formatProperty (util.js:822:15)
    at util.js:681:12
    at Array.map (native)
[12:07:27] 'dist' errored after 25 min
[12:07:27] TypeError in plugin "run-sequence(compress)"
Message:
    handler.state is not a function
Stack:
TypeError: handler.state is not a function
    at Object.inspect (/home/persei/dev/butter/butter-desktop/node_modules/when/lib/state.js:28:23)
    at formatValue (util.js:369:36)
    at formatProperty (util.js:822:15)
    at util.js:681:12
    at Array.map (native)
    at formatObject (util.js:680:15)
    at formatValue (util.js:620:16)
    at formatProperty (util.js:822:15)
    at util.js:681:12
    at Array.map (native)
```
Maybe it's related to memory, because I worked when i launched `gulp dist --platforms=osx64` alone

**Comment by jpita** [comment]
same on Mac
`Error: Cannot find module 'run-sequence'`

**Comment by ozkanpakdil** [comment]
linux mint
popcorn-desktop $ yarn gulp dist --platform=all
yarn gulp v1.0.1
$ gulp "dist" "--platform=all"
Branch: development
Commit: c2224970
Stylus files compiled in /home/mascix/tmp/tmp/popcorn-desktop/src/app/themes/
Vendors copied
Using v0.18.6 (sdk)
Create cache folder in /home/mascix/tmp/tmp/popcorn-desktop/cache/0.18.6-sdk
Using cache for: linux64
Create release folder in /home/mascix/tmp/tmp/popcorn-desktop/build/Popcorn-Time/linux64
Packaging tar for: linux64
linux64 tar packaged in /home/mascix/tmp/tmp/popcorn-desktop/build
Packaging deb for: linux64
linux64 deb packaged in /home/mascix/tmp/tmp/popcorn-desktop/build
No `nsis` task for linux64
Done in 599.34s.
