### ISSUE TITLE
Cannot build on Fedora 27 I get a gulp error

### ISSUE THREAD

**Issue by andreicristianpetcu** [popcorntime/popcorntime#777]
Operating System Version:
Fedora 27

Popcorn Time Version:
master, more specifically, this commi f381d448

Download date:
6th of May 2018

#### Expected Behaviour
I expected to be able to build it locally

#### Actual Behaviour
I was unable to build it locally.

#### Steps to reproduce the behaviour

```
$node --version
v8.11.1
$npm --version
6.0.0
$npm install -g bower gulp
$npm install
$bower install
$gulp build
[10:07:50] Using gulpfile ~/Dev/popcorn-desktop/gulpfile.js
[10:07:50] Starting 'build'...
[10:07:50] Starting 'injectgit'...
Branch: development
Commit: f381d448
[10:07:50] Finished 'injectgit' after 12 ms
[10:07:50] Starting 'css'...
Stylus files compiled in /home/andrei/Dev/popcorn-desktop/src/app/themes/
[10:07:52] Finished 'css' after 2.34 s
[10:07:52] Starting 'nwjs'...
{ Error: Command failed: npm ls --production=true --parseable=true
npm ERR! missing: mkdirp@0.5.1, required by node-pre-gyp@0.6.36
npm ERR! missing: rimraf@2.6.1, required by node-pre-gyp@0.6.36
npm ERR! missing: tar@2.2.1, required by node-pre-gyp@0.6.36
npm ERR! missing: minimist@0.0.8, required by mkdirp@0.5.1
npm ERR! missing: console-control-strings@1.1.0, required by npmlog@4.1.0
npm ERR! missing: readable-stream@2.2.9, required by are-we-there-yet@1.1.4
npm ERR! missing: console-control-strings@1.1.0, required by gauge@2.7.4
npm ERR! missing: string-width@1.0.2, required by gauge@2.7.4
npm ERR! missing: strip-ansi@3.0.1, required by gauge@2.7.4
npm ERR! missing: code-point-at@1.1.0, required by string-width@1.0.2
npm ERR! missing: is-fullwidth-code-point@1.0.0, required by string-width@1.0.2
npm ERR! missing: strip-ansi@3.0.1, required by string-width@1.0.2
npm ERR! missing: number-is-nan@1.0.1, required by is-fullwidth-code-point@1.0.0
npm ERR! missing: ansi-regex@2.1.1, required by strip-ansi@3.0.1
npm ERR! missing: string-width@1.0.2, required by wide-align@1.1.2
npm ERR! missing: combined-stream@1.0.5, required by request@2.81.0
npm ERR! missing: mime-types@2.1.15, required by request@2.81.0
npm ERR! missing: safe-buffer@5.0.1, required by request@2.81.0
npm ERR! missing: delayed-stream@1.0.0, required by combined-stream@1.0.5
npm ERR! missing: combined-stream@1.0.5, required by form-data@2.1.4
npm ERR! missing: mime-types@2.1.15, required by form-data@2.1.4
npm ERR! missing: boom@2.10.1, required by hawk@3.1.3
npm ERR! missing: hoek@2.16.3, required by hawk@3.1.3
npm ERR! missing: hoek@2.16.3, required by boom@2.10.1
npm ERR! missing: boom@2.10.1, required by cryptiles@2.0.5
npm ERR! missing: hoek@2.16.3, required by sntp@1.0.9
npm ERR! missing: extsprintf@1.0.2, required by jsprim@1.4.0
npm ERR! missing: extsprintf@1.0.2, required by verror@1.3.6
npm ERR! missing: mime-db@1.27.0, required by mime-types@2.1.15
npm ERR! missing: safe-buffer@5.0.1, required by tunnel-agent@0.6.0
npm ERR! missing: glob@7.1.2, required by rimraf@2.6.1
npm ERR! missing: fs.realpath@1.0.0, required by glob@7.1.2
npm ERR! missing: inflight@1.0.6, required by glob@7.1.2
npm ERR! missing: inherits@2.0.3, required by glob@7.1.2
npm ERR! missing: minimatch@3.0.4, required by glob@7.1.2
npm ERR! missing: once@1.4.0, required by glob@7.1.2
npm ERR! missing: path-is-absolute@1.0.1, required by glob@7.1.2
npm ERR! missing: once@1.4.0, required by inflight@1.0.6
npm ERR! missing: wrappy@1.0.2, required by inflight@1.0.6
npm ERR! missing: brace-expansion@1.1.7, required by minimatch@3.0.4
npm ERR! missing: balanced-match@0.4.2, required by brace-expansion@1.1.7
npm ERR! missing: concat-map@0.0.1, required by brace-expansion@1.1.7
npm ERR! missing: block-stream@0.0.9, required by tar@2.2.1
npm ERR! missing: fstream@1.0.11, required by tar@2.2.1
npm ERR! missing: inherits@2.0.3, required by tar@2.2.1
npm ERR! missing: inherits@2.0.3, required by block-stream@0.0.9
npm ERR! missing: graceful-fs@4.1.11, required by fstream@1.0.11
npm ERR! missing: inherits@2.0.3, required by fstream@1.0.11
npm ERR! missing: mkdirp@0.5.1, required by fstream@1.0.11
npm ERR! missing: rimraf@2.6.1, required by fstream@1.0.11
npm ERR! missing: fstream@1.0.11, required by tar-pack@3.4.0
npm ERR! missing: once@1.4.0, required by tar-pack@3.4.0
npm ERR! missing: readable-stream@2.2.9, required by tar-pack@3.4.0
npm ERR! missing: rimraf@2.6.1, required by tar-pack@3.4.0
npm ERR! missing: tar@2.2.1, required by tar-pack@3.4.0
npm ERR! missing: fstream@1.0.11, required by fstream-ignore@1.0.5
npm ERR! missing: inherits@2.0.3, required by fstream-ignore@1.0.5
npm ERR! missing: minimatch@3.0.4, required by fstream-ignore@1.0.5
npm ERR! missing: wrappy@1.0.2, required by once@1.4.0
npm ERR! missing: buffer-shims@1.0.0, required by readable-stream@2.2.9
npm ERR! missing: core-util-is@1.0.2, required by readable-stream@2.2.9
npm ERR! missing: inherits@2.0.3, required by readable-stream@2.2.9
npm ERR! missing: isarray@1.0.0, required by readable-stream@2.2.9
npm ERR! missing: process-nextick-args@1.0.7, required by readable-stream@2.2.9
npm ERR! missing: string_decoder@1.0.1, required by readable-stream@2.2.9
npm ERR! missing: util-deprecate@1.0.2, required by readable-stream@2.2.9
npm ERR! missing: safe-buffer@5.0.1, required by string_decoder@1.0.1

    at ChildProcess.exithandler (child_process.js:275:12)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
  killed: false,
  code: 1,
  signal: null,
  cmd: 'npm ls --production=true --parseable=true' }
[10:07:54] Finished 'nwjs' after 2.39 s
[10:07:54] Finished 'build' after 4.74 s
```

**Comment by Persei08** [comment]
I think it's related to npm version because i got the same issue with npm 5 and 6.

Install latest npm 4.x.x version (`sudo npm install -g npm@latest-4`) and retry.

I don't think it's related to #776 or #781, but more with #774.

Please test and tell us.

**Comment by christian130** [comment]
hi, you have to ~~download the latest NODE as long as the NPM and then~~ do a downgrade... if everything is OK in your computer, it should be compiled... please refer to #774 
edit:
@Persei08 you should need to download the LTS version of node (which comes with npm), the node LTS version is the 8~
#774

**Comment by christian130** [comment]
https://we.tl/uttfaHmSiK

**Comment by Persei08** [comment]
No!! you don't need the latest node or npm versions. You need npm 4.x.x. with the node 7 or 8.

@christian130 There is no point into sharing your packaged version here.

**Comment by andreicristianpetcu** [comment]
@Persei08 thank you for your input! I tested with node 8 and npm 4 and I managed to build. When I start it, it fails just like the installed version :(

@christian130 I'm using the LTS

**Comment by christian130** [comment]
if it fails it could be due to VIDEO performance... and therefore some of driver issues... could you just add print screen?... and if you was successfully to build it, please then go to the log file and copy paste

**Comment by Persei08** [comment]
@andreicristianpetcu  I think you can close this. We have report #776 for the crash under fedora.

**Comment by andreicristianpetcu** [comment]
@christian130 it just fails on startup. I see less than a second the window and then it stops. Where can I find the log files? I wanted to build this locally so I can get info about why it fails and share it on the other issue.

If somebody starts working on #776 I can even build from branch locally and test if it works before it gets merged.

**Comment by andreicristianpetcu** [comment]
This is what I get:

```bash
$gulp run 
[14:50:20] Using gulpfile ~/Dev/popcorn-desktop/gulpfile.js
[14:50:20] Starting 'run'...
Running linux64 from cache
Popcorn-Time exited with code 0
[14:50:24] Finished 'run' after 3.71 s
```

**Comment by Persei08** [comment]
We don't know if this is something to fix on PT side.
