### ISSUE TITLE
Main screen lagging and crashing

### ISSUE THREAD

**Issue by raphaelbernardino** [popcorntime/popcorntime#780]
#### Operating System Version:
Linux Ubuntu 16.04

#### Popcorn Time Version:
Latest? I don't know. But I cloned from github.

#### Download date:
2018-09-05

#### Expected Behaviour
Load main screen.
...

#### Actual Behaviour
Loads main screen but crashes very after. In fact, it does not crash, but stops responding.
...

#### Steps to reproduce the behaviour
1. Open.
2. Move mouse around to select a title.
3.1. Not responding. Tada!
3.2 [Still responding] Clicks on a title.
4. [tries to] Start download... CRASH!

Maybe related to #736 

#### [Update] Adding log error.
```
$ ./Popcorn-Time 
[23535:23535:0509/224830:ERROR:sandbox_linux.cc(345)] InitializeSandbox() called with multiple threads in process gpu-process. 
fs.js:557
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: EMFILE: too many open files, open '/home/username/.config/Popcorn-Time/Default/logs.txt'
    at Object.fs.openSync (fs.js:557:18)
    at Object.fs.writeFileSync (fs.js:1214:33)
    at Object.fs.appendFileSync (fs.js:1260:6)
    at emitOne (events.js:96:13)
    at process.emit (events.js:188:7)
    at process._fatalException (bootstrap_node.js:309:26)
fs.js:557
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: EMFILE: too many open files, open '/home/username/.config/Popcorn-Time/Default/logs.txt'
    at Object.fs.openSync (fs.js:557:18)
    at Object.fs.writeFileSync (fs.js:1214:33)
    at Object.fs.appendFileSync (fs.js:1260:6)
    at emitOne (events.js:96:13)
    at process.emit (events.js:188:7)
    at process._fatalException (bootstrap_node.js:309:26)
fs.js:557
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: EMFILE: too many open files, open '/home/username/.config/Popcorn-Time/Default/logs.txt'
    at Object.fs.openSync (fs.js:557:18)
    at Object.fs.writeFileSync (fs.js:1214:33)
    at Object.fs.appendFileSync (fs.js:1260:6)
    at emitOne (events.js:96:13)
    at process.emit (events.js:188:7)
    at process._fatalException (bootstrap_node.js:309:26)
```

#### logs.txt
```
Error: listen EMFILE 0.0.0.0:45850
    at Object.exports._errnoException (util.js:1022:11)
    at exports._exceptionWithHostPort (util.js:1045:20)
    at Server._listen2 (net.js:1249:19)
    at listen (net.js:1298:10)
    at Server.listen (net.js:1376:9)
    at process._tickCallback (internal/process/next_tick.js:103:7)

Can't play video %s: %s, code %d

subtitleProvider.fetch()
```

**Comment by Persei08** [comment]
Please provide the commit id after `HEAD(`. (see gif below)
![pt_version number](https://user-images.githubusercontent.com/22459458/39890499-401a5576-549b-11e8-95ef-87e7d422861f.gif)

**Comment by raphaelbernardino** [comment]
Commit is [f381d448](https://github.com/popcorn-official/popcorn-desktop/commit/f381d44885c962a42587c726a24b3092cdc91ab8)

![screenshot from 2018-05-11 09-10-39](https://user-images.githubusercontent.com/920682/39923739-430a7332-54fb-11e8-8392-3a797061361a.png)

**Comment by raphaelbernardino** [comment]
[New "bugs" leading to crash]
Movie: Den of Thieves. (all other movies/covers works fine)

```
$ ./Popcorn-Time 
[6782:6782:0511/092613:ERROR:sandbox_linux.cc(345)] InitializeSandbox() called with multiple threads in process gpu-process. 
[6782:6782:0511/092622:ERROR:gles2_cmd_decoder.cc(16038)] [.RenderWorker-0x564d90040fe0]GL ERROR :GL_INVALID_OPERATION : glBindTexImage2DCHROMIUM: no image found with the given ID
[6782:6782:0511/092622:ERROR:gles2_cmd_decoder.cc(15340)] [.RenderWorker-0x564d90040fe0]GL ERROR :GL_INVALID_VALUE : glCopySubTextureCHROMIUM: source texture has no level 0
[6782:6782:0511/092622:ERROR:gles2_cmd_decoder.cc(16038)] [.RenderWorker-0x564d90040fe0]GL ERROR :GL_INVALID_OPERATION : glBindTexImage2DCHROMIUM: no image found with the given ID
[6782:6782:0511/092622:ERROR:gles2_cmd_decoder.cc(15340)] [.RenderWorker-0x564d90040fe0]GL ERROR :GL_INVALID_VALUE : glCopySubTextureCHROMIUM: source texture has no level 0
[6782:6782:0511/092622:ERROR:gles2_cmd_decoder.cc(16038)] [.RenderWorker-0x564d90040fe0]GL ERROR :GL_INVALID_OPERATION : glBindTexImage2DCHROMIUM: no image found with the given ID
[6782:6782:0511/092622:ERROR:gles2_cmd_decoder.cc(15340)] [.RenderWorker-0x564d90040fe0]GL ERROR :GL_INVALID_VALUE : glCopySubTextureCHROMIUM: source texture has no level 0
[6782:6782:0511/092622:ERROR:gles2_cmd_decoder.cc(16038)] [.RenderWorker-0x564d90040fe0]GL ERROR :GL_INVALID_OPERATION : glBindTexImage2DCHROMIUM: no image found with the given ID
[6782:6782:0511/092622:ERROR:gles2_cmd_decoder.cc(15340)] [.RenderWorker-0x564d90040fe0]GL ERROR :GL_INVALID_VALUE : glCopySubTextureCHROMIUM: source texture has no level 0
[6782:6782:0511/092623:ERROR:gles2_cmd_decoder.cc(16038)] [.RenderWorker-0x564d90040fe0]GL ERROR :GL_INVALID_OPERATION : glBindTexImage2DCHROMIUM: no image found with the given ID
[6782:6782:0511/092623:ERROR:gles2_cmd_decoder.cc(15340)] [.RenderWorker-0x564d90040fe0]GL ERROR :GL_INVALID_VALUE : glCopySubTextureCHROMIUM: source texture has no level 0
[6782:6782:0511/092623:ERROR:gpu_command_buffer_stub.cc(1031)] Image with ID doesn't exist.
[6782:6782:0511/092623:ERROR:gpu_command_buffer_stub.cc(1031)] Image with ID doesn't exist.
[6782:6782:0511/092623:ERROR:gpu_command_buffer_stub.cc(1031)] Image with ID doesn't exist.
[6782:6782:0511/092623:ERROR:gpu_command_buffer_stub.cc(1031)] Image with ID doesn't exist.
[6782:6782:0511/092623:ERROR:gpu_command_buffer_stub.cc(1031)] Image with ID doesn't exist.
```

**Comment by Persei08** [comment]
Can you try to disable "Activate update seeding" option. 
For me it greatly reduced the number of freezes

**Comment by Persei08** [comment]
I think a workaround is to start PT with `--disable-gpu` argument ...until a solution is found

**Comment by klorydryk** [comment]
I got the same problem, described in #786 
The workaround is not working, and logs.txt contains:

> Error: listen EADDRINUSE :::41974
    at Object.exports._errnoException (util.js:1022:11)
    at exports._exceptionWithHostPort (util.js:1045:20)
    at Server._listen2 (net.js:1262:14)
    at listen (net.js:1298:10)
    at Server.listen (net.js:1376:9)
    at process._tickCallback (internal/process/next_tick.js:103:7)
    Can't play video %s: %s, code %d

**Comment by Persei08** [comment]
@klorydryk have you disabled "Activate update seeding" option?

**Comment by klorydryk** [comment]
@Persei08 OMG it works!
Thanks! Sorry I didn't tried this before. What is the problem with this option?

**Comment by Persei08** [comment]
Great, if you can test that for few days and give feedback later if it work, improve, or finally doesn't help, it will be great ;)

I think there is an issue with the "seeding update" feature. I don't understand exactly all the details, but my understanding is it run another instance of webtorrent to seed the update, and for some reasons generating some freezes.
