### ISSUE TITLE
Popcorntime freezing randomly

### ISSUE THREAD

**Issue by zskamljic** [popcorntime/popcorntime#806]
Operating System Version:
Linux 4.16.13-1

Popcorn Time Version:
3.10

Download date:
6.7.2018 (installed previously, but reinstalled/wiped multiple times)

#### Expected Behaviour
Perform normally

#### Actual Behaviour
Freezes and becomes completely unresponsive to user input and has to be force killed

#### Steps to reproduce the behaviour
Perform virtually any action, although it occurred more often when browsing series with multiple seasons, possibly clicking "mark as watched". 

I've managed to get some output:

```
fs.js:557
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: EMFILE: too many open files, open '/home/zan/.config/Popcorn-Time/Default/logs.txt'
    at Object.fs.openSync (fs.js:557:18)
    at Object.fs.writeFileSync (fs.js:1214:33)
    at Object.fs.appendFileSync (fs.js:1260:6)
    at emitOne (events.js:96:13)
    at process.emit (events.js:188:7)
    at process._fatalException (bootstrap_node.js:309:26)
[24885:24885:0606/164059:ERROR:gles2_cmd_decoder.cc(16038)] [.RenderWorker-0x56396b42acf0]GL ERROR :GL_INVALID_OPERATION : glBindTexImage2DCHROMIUM: no image found with the given ID
[24885:24885:0606/164059:ERROR:gles2_cmd_decoder.cc(15340)] [.RenderWorker-0x56396b42acf0]GL ERROR :GL_INVALID_VALUE : glCopySubTextureCHROMIUM: source texture has no level 0
[24885:24885:0606/164059:ERROR:gles2_cmd_decoder.cc(16038)] [.RenderWorker-0x56396b42acf0]GL ERROR :GL_INVALID_OPERATION : glBindTexImage2DCHROMIUM: no image found with the given ID
[24885:24885:0606/164059:ERROR:gles2_cmd_decoder.cc(15340)] [.RenderWorker-0x56396b42acf0]GL ERROR :GL_INVALID_VALUE : glCopySubTextureCHROMIUM: source texture has no level 0
[24885:24885:0606/164059:ERROR:gles2_cmd_decoder.cc(16081)] [.RenderWorker-0x56396b42acf0]GL ERROR :GL_INVALID_OPERATION : glReleaseTexImage2DCHROMIUM: no image found with the given ID
[24885:24885:0606/164059:ERROR:gles2_cmd_decoder.cc(16038)] [.RenderWorker-0x56396b42acf0]GL ERROR :GL_INVALID_OPERATION : glBindTexImage2DCHROMIUM: no image found with the given ID
[24885:24885:0606/164059:ERROR:gles2_cmd_decoder.cc(15340)] [.RenderWorker-0x56396b42acf0]GL ERROR :GL_INVALID_VALUE : glCopySubTextureCHROMIUM: source texture has no level 0
[24885:24885:0606/164100:ERROR:gpu_command_buffer_stub.cc(1031)] Image with ID doesn't exist.
[24885:24885:0606/164100:ERROR:gpu_command_buffer_stub.cc(1031)] Image with ID doesn't exist.

```

**Comment by Persei08** [comment]
Seem to be same issue than #786 and could be related to #780 too.

Restart PT, quickly go in settings, check "show advanced settings", uncheck "Activate Update seeding", restart PT.

If it freeze again and still display error with gles2, as a workaround, you can add the argument `--disable-gpu` when launching PT .

**Comment by zskamljic** [comment]
Seems to help for now, I'll report back if it happens again, it's kind of hard to reproduce due to it happening asporadically

**Comment by trosel** [comment]
@Persei08 Are you referring to this option? 
![image](https://user-images.githubusercontent.com/1299322/41789724-19693ef2-7605-11e8-8a41-4710744d5767.png)

What does that do? Why would it cause freezing during playback?

**Comment by Persei08** [comment]
@WildYorkies , No, check this screenshot, the second option:

![screenshot_2018-06-23_00-18-26](https://user-images.githubusercontent.com/22459458/41801463-029d2d2a-767b-11e8-9bd6-afc07abe8232.png)

edit: I just suggest that for dev builds.

**Comment by DesenvolvimentoAI** [comment]
Is there a solution for this? I have problem in Ubuntu 18.04, PT worked well two days until got
InitializeSandbox() called with multiple threads in process gpu-process.
